## just debugging

In [16]:
import anndata as ad
import numpy as np

In [2]:
import scanpy as sc

In [17]:
adata_out = sc.read_h5ad("/nfs/home/students/m.back/swarm/backend/uploads/job_1772910016214_e7859f94-34ff-427d-bde2-96566542db41/kackhaufen1/adata_tg_scores.h5ad")

In [18]:
adata_out.obsm

AxisArrays with keys: chromvar_spot_scores, spatial, tangram_ct_pred

In [19]:
adata_out.uns.keys()

dict_keys(['chromvar_gearyC', 'chromvar_moranI', 'chromvar_motifs', 'neighbors', 'overlap_genes', 'rank_genes_groups', 'spatial', 'training_genes'])

In [13]:
adata_out.uns["chromvar_moranI"]

,TF,motif_id,I,pval_norm,var_norm,pval_z_sim,pval_sim,var_sim,pval_norm_fdr_bh,pval_z_sim_fdr_bh,pval_sim_fdr_bh
179,ALX3,MA0634.2,0.018970,0.104056,0.000246,5.398901e-02,0.049950,0.000138,0.135048,0.070271,0.065062
181,ARGFX,MA1463.2,0.017350,0.123931,0.000246,8.713555e-02,0.079920,0.000147,0.156634,0.108768,0.099935
182,ARNT,MA0259.2,0.147036,0.000000,0.000246,0.000000e+00,0.000999,0.000245,0.000000,0.000000,0.001782
183,ARNT2,MA1464.2,0.038907,0.005717,0.000246,1.183340e-03,0.003996,0.000159,0.009811,0.001960,0.006328
185,ASCL1,MA1631.2,0.325770,0.000000,0.000246,0.000000e+00,0.000999,0.000350,0.000000,0.000000,0.001782
...,...,...,...,...,...,...,...,...,...,...,...
132,ZSCAN16,MA2100.1,0.021954,0.073688,0.000246,3.421463e-02,0.033966,0.000137,0.101110,0.046592,0.046166
177,ZSCAN21,MA2336.1,0.063145,0.000023,0.000246,6.458758e-07,0.000999,0.000166,0.000061,0.000002,0.001782
718,ZSCAN29,MA1602.2,0.028827,0.029591,0.000246,9.621980e-03,0.008991,0.000158,0.044604,0.014443,0.013552
719,ZSCAN31,MA1722.2,0.027569,0.035406,0.000246,9.855589e-03,0.006993,0.000142,0.052597,0.014763,0.010744
96,ZSCAN4,MA1155.1,0.053737,0.000256,0.000246,1.304974e-05,0.000999,0.000164,0.000593,0.000030,0.001782

In [15]:
import pandas as pl
pl.read_csv("/nfs/home/students/m.back/swarm/backend/uploads/run_new_multiome_pipeline/dumpase1/diff_motif_activity_top_motifs.csv")

,fibroblast_vs_rest.p_val,fibroblast_vs_rest.avg_diff,fibroblast_vs_rest.pct.1,fibroblast_vs_rest.pct.2,fibroblast_vs_rest.p_val_adj,fibroblast_vs_rest.motif,B.cell_vs_rest.p_val,B.cell_vs_rest.avg_diff,B.cell_vs_rest.pct.1,B.cell_vs_rest.pct.2,...,endothelial.cell_vs_rest.pct.1,endothelial.cell_vs_rest.pct.2,endothelial.cell_vs_rest.p_val_adj,endothelial.cell_vs_rest.motif,myeloid.cell_vs_rest.p_val,myeloid.cell_vs_rest.avg_diff,myeloid.cell_vs_rest.pct.1,myeloid.cell_vs_rest.pct.2,myeloid.cell_vs_rest.p_val_adj,myeloid.cell_vs_rest.motif
0,7.418400e-40,0.840295,0.630,0.333,5.341248e-37,MA1123.3,9.853859e-15,0.669326,0.477,0.273,...,0.905,0.456,0.000168,MA0772.2,0.015452,0.535974,0.889,0.526,1,MA0724.1
1,2.704026e-36,0.772967,0.594,0.311,1.946899e-33,MA0698.2,9.853859e-15,0.669326,0.477,0.273,...,0.952,0.414,0.000002,MA1721.2,0.020152,0.518683,0.778,0.460,1,MA2334.1
2,9.189919e-39,0.716901,0.569,0.271,6.616742e-36,MA1638.2,9.853859e-15,0.669326,0.477,0.273,...,0.857,0.442,0.008198,MA0653.1,0.045004,0.490225,0.778,0.532,1,MA1544.2

## check new spatial healthy data

In [12]:
path_new = "/nfs/home/students/m.back/swarm/backend/uploads/job_1772186189938_9d92b4a8-7fd3-4bcd-b61a-d9727df81b0b/GSM6592048_M1_prepro.h5ad"
path_old = "/nfs/home/students/m.back/swarm/backend/uploads/job_1769087502939_599b22f7-283d-400d-853c-5f62100ada2e/adata.h5ad"
path = "/nfs/home/students/m.back/swarm/backend/data/GSM6592048_M1_prepro.h5ad"

In [13]:
adata_new = ad.read_h5ad(path)

In [17]:
adata_new

AnnData object with n_obs × n_vars = 1275 × 36601

In [15]:
adata_new.var

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[36601 rows x 0 columns]

In [6]:
adata_old = ad.read_h5ad(path_old)

In [7]:
adata_old

AnnData object with n_obs × n_vars = 1448 × 22616
    obs: 'in_tissue', 'array_row', 'array_col', 'suspension_type', 'assay_ontology_term_id', 'Sample_ID', 'organism_ontology_term_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'pathologist_annotation', 'B-cells', 'CAFs', 'Cancer Epithelial', 'Endothelial', 'Myeloid', 'Normal Epithelial', 'PVL', 'T-cells', 'stereoscope_annotation', 'cell_type_ontology_term_id', 'is_primary_data', 'treatment', 'donor_id', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'leiden', 'uniform_density', 'rna_count_based_density'
    var: 'feature_types', 'genome', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type', 'ensemble_id', 'n_cells', 'sparsity'
    uns: 'cell_comp_tf_activity_global_scores', 'citation', 'gearyC', 'genie_genesets', 'leiden', 'leiden_centrality_scores', 'leiden_co_occurrence', 'leiden_nhood_enrichment', 'liana_columns', 'ligand_receptor_global_scores', 'moranI', 'neighbors', 'overlap_genes', 'pca', 'schema_reference', 'schema_version', 'spatial', 'spatial_neighbors', 'sponge_genesets', 'title', 'training_genes', 'umap'
    obsm: 'X_pca', 'X_umap', 'aucell_scores_genie3', 'aucell_scores_sponge', 'cell_comp_tf_activity_category', 'cell_comp_tf_activity_cosine_similarity', 'celltype_scores', 'ligand_receptor_NMF_factors', 'ligand_receptor_category', 'ligand_receptor_cosine_similarity', 'ligand_receptor_p_value', 'pathway_activity_padj_mlm', 'pathway_activity_score_mlm', 'spatial', 'spongeffects_GSVA_scores_genie3', 'spongeffects_GSVA_scores_sponge', 'spongeffects_ssGSEA_scores_genie3', 'spongeffects_ssGSEA_scores_sponge', 'tf_activity_padj_ulm', 'tf_activity_score_ulm', 'viper_scores_genie3'
    varm: 'PCs'
    obsp: 'connectivities', 'distances', 'spatial_connectivities', 'spatial_distances'

In [3]:
adata = ad.read_h5ad(path_new)

In [11]:
adata.var

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[36601 rows x 0 columns]

In [10]:
adata.obs

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1275 rows x 0 columns]

### integration of differential motif activity

In [3]:
path_map = "../backend/uploads/job_1768478211396_76193c44-3781-4b8b-b9ef-fc7702b4a617/plasmidpoop/adata_map.h5ad"

adata = ad.read_h5ad(path_map)

In [ ]:
df = pd.DataFrame( 
    adata.X,  # convert sparse to dense
    index=adata.obs_names,
    columns=adata.var_names)
df.to_csv("../backend/uploads/job_1768478211396_76193c44-3781-4b8b-b9ef-fc7702b4a617/plasmidpoop/tangram_map.csv")

In [14]:
adata.var.to_csv("../backend/uploads/job_1768478211396_76193c44-3781-4b8b-b9ef-fc7702b4a617/plasmidpoop/meta_spatial.csv")

In [11]:
adata.write_zarr("../backend/uploads/job_1768478211396_76193c44-3781-4b8b-b9ef-fc7702b4a617/plasmidpoop//tangram_map.zarr")

In [6]:
tg_tmp = ad.read_h5ad("/workspaces/swarm/backend/data/multiome_data/adata_tg_scores_dif_motif_act.h5ad")

In [7]:
tg_tmp

AnnData object with n_obs × n_vars = 1448 × 1714
    obs: 'in_tissue', 'array_row', 'array_col', 'suspension_type', 'assay_ontology_term_id', 'Sample_ID', 'organism_ontology_term_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'pathologist_annotation', 'B-cells', 'CAFs', 'Cancer Epithelial', 'Endothelial', 'Myeloid', 'Normal Epithelial', 'PVL', 'T-cells', 'stereoscope_annotation', 'cell_type_ontology_term_id', 'is_primary_data', 'treatment', 'donor_id', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'leiden', 'uniform_density', 'rna_count_based_density'
    var: 'vf_vst_counts_mean', 'vf_vst_counts_variance', 'vf_vst_counts_variance.expected', 'vf_vst_counts_variance.standardized', 'vf_vst_counts_variable', 'vf_vst_counts_rank', 'var.features', 'var.features.rank', 'n_cells', 'sparsity', 'is_training'
    uns: 'chromvar_gearyC', 'chromvar_moranI', 'chromvar_motifs', 'overlap_genes', 'spatial', 'training_genes'
    obsm: 'chromvar_spot_scores', 'spatial', 'tangram_ct_pred'

### other stuff

In [32]:
anndata = "/nfs/home/students/m.back/swarm/backend/data/adata.h5ad"
og_ad = ad.read_h5ad(anndata)

In [38]:
og_ad

AnnData object with n_obs × n_vars = 1448 × 22616
    obs: 'in_tissue', 'array_row', 'array_col', 'suspension_type', 'assay_ontology_term_id', 'Sample_ID', 'organism_ontology_term_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'pathologist_annotation', 'B-cells', 'CAFs', 'Cancer Epithelial', 'Endothelial', 'Myeloid', 'Normal Epithelial', 'PVL', 'T-cells', 'stereoscope_annotation', 'cell_type_ontology_term_id', 'is_primary_data', 'treatment', 'donor_id', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'leiden', 'uniform_density', 'rna_count_based_density'
    var: 'feature_types', 'genome', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type', 'ensemble_id', 'n_cells', 'sparsity'
    uns: 'cell_comp_tf_activity_global_scores', 'citation', 'gearyC', 'genie_genesets', 'leiden', 'leiden_centrality_scores', 'leiden_co_occurrence', 'leiden_nhood_enrichment', 'liana_columns', 'ligand_receptor_global_scores', 'moranI', 'neighbors', 'overlap_genes', 'pca', 'schema_reference', 'schema_version', 'spatial', 'spatial_neighbors', 'sponge_genesets', 'title', 'training_genes', 'umap'
    obsm: 'X_pca', 'X_umap', 'aucell_scores_genie3', 'aucell_scores_sponge', 'cell_comp_tf_activity_category', 'cell_comp_tf_activity_cosine_similarity', 'celltype_scores', 'ligand_receptor_NMF_factors', 'ligand_receptor_category', 'ligand_receptor_cosine_similarity', 'ligand_receptor_p_value', 'pathway_activity_padj_mlm', 'pathway_activity_score_mlm', 'spatial', 'spongeffects_GSVA_scores_genie3', 'spongeffects_GSVA_scores_sponge', 'spongeffects_ssGSEA_scores_genie3', 'spongeffects_ssGSEA_scores_sponge', 'tf_activity_padj_ulm', 'tf_activity_score_ulm', 'viper_scores_genie3'
    varm: 'PCs'
    obsp: 'connectivities', 'distances', 'spatial_connectivities', 'spatial_distances'

In [3]:
tg_tmp = ad.read_h5ad("/nfs/home/students/m.back/swarm/backend/data/multiome_data/adata.h5ad")

In [8]:
tg_tmp.uns["gearyC"]

                          C      pval_norm  var_norm  pval_norm_fdr_bh
MALAT1             0.246455   0.000000e+00  0.000232      0.000000e+00
IGHA1              0.468705  2.666089e-267  0.000232     2.912864e-265
IGKC               0.480034  3.986214e-256  0.000232     4.334241e-254
COL11A1            0.525611  1.340872e-213  0.000232     1.450965e-211
MT-CO1             0.532177  8.577147e-208  0.000232     9.237178e-206
...                     ...            ...       ...               ...
ENSG00000250602.6  1.422222   0.000000e+00  0.000232      0.000000e+00
LINC02705          1.422222   0.000000e+00  0.000232      0.000000e+00
ENSG00000237390.1  1.422222   0.000000e+00  0.000232      0.000000e+00
LINC00319          1.422222   0.000000e+00  0.000232      0.000000e+00
KRT13              1.533135   0.000000e+00  0.000232      0.000000e+00

[22616 rows x 4 columns]

In [5]:
tmp

AnnData object with n_obs × n_vars = 1448 × 2000
    obs: 'in_tissue', 'array_row', 'array_col', 'suspension_type', 'assay_ontology_term_id', 'Sample_ID', 'organism_ontology_term_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'pathologist_annotation', 'B-cells', 'CAFs', 'Cancer Epithelial', 'Endothelial', 'Myeloid', 'Normal Epithelial', 'PVL', 'T-cells', 'stereoscope_annotation', 'cell_type_ontology_term_id', 'is_primary_data', 'treatment', 'donor_id', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'leiden', 'uniform_density', 'rna_count_based_density'
    var: 'vf_vst_counts_mean', 'vf_vst_counts_variance', 'vf_vst_counts_variance.expected', 'vf_vst_counts_variance.standardized', 'vf_vst_counts_variable', 'vf_vst_counts_rank', 'var.features', 'var.features.rank', 'n_cells', 'sparsity', 'is_training'
    uns: 'chromvar_gearyC', 'chromvar_moranI', 'chromvar_motifs', 'neighbors', 'overlap_genes', 'spatial', 'training_genes'
    obsm: 'chromvar_spot_scores', 'spatial', 'tangram_ct_pred'

In [2]:
tmp=ad.read_h5ad("/nfs/home/students/m.back/swarm/backend/uploads/job_1765803539341_a9f80e29-1a69-43ae-adba-8776d9d2807f/dumpase1/adata_tg_scores.h5ad")

In [13]:
tmp.uns["chromvar_gearyC"].head()

,TF,motif_id,C,pval_norm,var_norm,pval_z_sim,pval_sim,var_sim,pval_norm_fdr_bh,pval_z_sim_fdr_bh,pval_sim_fdr_bh
179,ALX3,MA0634.2,1.001934,4.481267e-01,0.00022,1.973358e-01,0.195804,0.000121,4.544473e-01,2.127202e-01,0.211069
181,ARGFX,MA1463.2,0.974412,4.221382e-02,0.00022,1.418033e-02,0.016983,0.000127,5.488560e-02,1.877653e-02,0.022081
182,ARNT,MA0259.2,0.912653,1.928600e-09,0.00022,4.261837e-14,0.000999,0.000156,6.540864e-09,1.692962e-13,0.001596
183,ARNT2,MA1464.2,0.944716,9.648080e-05,0.00022,9.055137e-06,0.000999,0.000143,2.057122e-04,1.764402e-05,0.001596
184,ASCL1,MA1100.3,0.921212,5.390709e-08,0.00022,1.901183e-10,0.000999,0.000161,1.642339e-07,5.866739e-10,0.001596

In [17]:
len(tmp.uns["chromvar_motifs"])

719

In [11]:
tmp.obsm["chromvar_spot_scores"]

array([[ 0.11191246,  0.00767777, -0.14373648, ..., -0.15734948,
        -0.11405548,  0.03134579],
       [-0.07560457,  0.01445961, -0.00481305, ...,  0.04790889,
         0.04910105, -0.0478431 ],
       [-0.06798503, -0.08232091, -0.06707779, ..., -0.08640496,
        -0.14012131,  0.05162521],
       ...,
       [-0.20686738, -0.32687622,  0.01075154, ..., -0.4878794 ,
        -0.12704569, -0.3495685 ],
       [-0.00783307, -0.00370591, -0.09384505, ..., -0.08892696,
         0.10063966,  0.04991449],
       [-0.12584892, -0.13311861, -0.06629133, ..., -0.1024716 ,
        -0.11180927,  0.00539224]], shape=(1448, 719), dtype=float32)

In [14]:
tmp

AnnData object with n_obs × n_vars = 1448 × 2000
    obs: 'in_tissue', 'array_row', 'array_col', 'suspension_type', 'assay_ontology_term_id', 'Sample_ID', 'organism_ontology_term_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'pathologist_annotation', 'B-cells', 'CAFs', 'Cancer Epithelial', 'Endothelial', 'Myeloid', 'Normal Epithelial', 'PVL', 'T-cells', 'stereoscope_annotation', 'cell_type_ontology_term_id', 'is_primary_data', 'treatment', 'donor_id', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'leiden', 'uniform_density', 'rna_count_based_density'
    var: 'vf_vst_counts_mean', 'vf_vst_counts_variance', 'vf_vst_counts_variance.expected', 'vf_vst_counts_variance.standardized', 'vf_vst_counts_variable', 'vf_vst_counts_rank', 'var.features', 'var.features.rank', 'n_cells', 'sparsity', 'is_training'
    uns: 'chromvar_gearyC', 'chromvar_moranI', 'chromvar_motifs', 'neighbors', 'overlap_genes', 'spatial', 'training_genes'
    obsm: 'chromvar_spot_scores', 'spatial', 'tangram_ct_pred'

### for a given list of motifs: add up the chromvar scores:

In [19]:
motif_list = ['MA1538.1', 'MA1539.1','MA1981.2', 'MA1728.2']

In [ ]:
def sum_motif_scores(adata, motif_list):
    chromvar_motifs = adata.uns["chromvar_motifs"]
    idx = np.where(np.isin(chromvar_motifs, motif_list))[0]
    return adata.obsm["chromvar_spot_scores"][:, idx].sum(axis=1)

In [ ]:
chromvar_motifs = tmp.uns["chromvar_motifs"]
idx = np.where(np.isin(chromvar_motifs, 'MA1538.1'))[0]
tmp.obsm["chromvar_spot_scores"][:, idx].sum(axis=1)

array([[-0.26159358],
       [-0.08317499],
       [-0.04246549],
       ...,
       [-0.20126258],
       [ 0.07789025],
       [-0.14468893]], shape=(1448, 1), dtype=float32)

In [46]:
tmp.uns["chromvar_motifs"]

array(['MA0071.1', 'MA0074.1', 'MA0101.1', 'MA0107.1', 'MA0115.1',
       'MA0119.1', 'MA0130.1', 'MA0149.1', 'MA0155.1', 'MA0159.1',
       'MA0163.1', 'MA0468.1', 'MA0258.2', 'MA0595.1', 'MA0596.1',
       'MA0599.1', 'MA0613.1', 'MA0636.1', 'MA0641.1', 'MA0042.2',
       'MA0033.2', 'MA0153.2', 'MA0486.2', 'MA0653.1', 'MA0655.1',
       'MA0660.1', 'MA0663.1', 'MA0665.1', 'MA0667.1', 'MA0669.1',
       'MA0678.1', 'MA0068.2', 'MA0083.3', 'MA0009.2', 'MA0689.1',
       'MA0691.1', 'MA0696.1', 'MA0713.1', 'MA0715.1', 'MA0724.1',
       'MA0729.1', 'MA0730.1', 'MA0731.1', 'MA0472.2', 'MA0736.1',
       'MA0737.1', 'MA0741.1', 'MA0088.2', 'MA0758.1', 'MA0770.1',
       'MA0771.1', 'MA0773.1', 'MA0774.1', 'MA0776.1', 'MA0777.1',
       'MA0105.4', 'MA0780.1', 'MA0783.1', 'MA0787.1', 'MA0788.1',
       'MA0789.1', 'MA0792.1', 'MA0794.1', 'MA0795.1', 'MA0796.1',
       'MA0797.1', 'MA0511.2', 'MA0801.1', 'MA0803.1', 'MA0805.1',
       'MA0806.1', 'MA0807.1', 'MA0808.1', 'MA0813.1', 'MA0815.1',
       'MA0822.1', 'MA0823.1', 'MA0826.1', 'MA0827.1', 'MA0838.1',
       'MA0845.1', 'MA0032.2', 'MA0848.1', 'MA0849.1', 'MA0850.1',
       'MA0855.1', 'MA0856.1', 'MA0525.2', 'MA0106.3', 'MA0862.1',
       'MA0863.1', 'MA0024.3', 'MA0866.1', 'MA0872.1', 'MA1124.1',
       'MA1155.1', 'MA1127.1', 'MA1129.1', 'MA1136.1', 'MA1420.1',
       'MA1421.1', 'MA1468.1', 'MA1485.1', 'MA1489.1', 'MA1493.1',
       'MA1509.1', 'MA1538.1', 'MA1539.1', 'MA1555.1', 'MA1556.1',
       'MA1557.1', 'MA1570.1', 'MA1571.1', 'MA1572.1', 'MA1580.1',
       'MA1587.1', 'MA1588.1', 'MA1594.1', 'MA1596.1', 'MA1597.1',
       'MA0158.2', 'MA0912.2', 'MA0623.2', 'MA2093.1', 'MA2094.1',
       'MA2096.1', 'MA1715.1', 'MA2097.1', 'MA2098.1', 'MA2099.1',
       'MA1718.1', 'MA2100.1', 'MA2101.1', 'MA2102.1', 'MA1931.1',
       'MA1957.1', 'MA1962.1', 'MA1972.1', 'MA1980.1', 'MA1985.1',
       'MA2117.1', 'MA2118.1', 'MA2119.1', 'MA2120.1', 'MA2121.1',
       'MA0079.5', 'MA0509.3', 'MA0516.3', 'MA0607.2', 'MA0685.2',
       'MA0740.2', 'MA0742.2', 'MA0798.3', 'MA0818.2', 'MA0821.2',
       'MA0831.3', 'MA0878.3', 'MA0884.2', 'MA1511.2', 'MA1532.2',
       'MA1547.2', 'MA1563.2', 'MA1601.2', 'MA1633.2', 'MA2324.1',
       'MA2325.1', 'MA2326.1', 'MA2327.1', 'MA2328.1', 'MA2329.1',
       'MA2330.1', 'MA2331.1', 'MA2332.1', 'MA2333.1', 'MA2334.1',
       'MA2335.1', 'MA2336.1', 'MA2341.1', 'MA0634.2', 'MA0690.3',
       'MA1463.2', 'MA0259.2', 'MA1464.2', 'MA1100.3', 'MA1631.2',
       'MA1632.2', 'MA0605.3', 'MA0833.3', 'MA1466.2', 'MA0834.2',
       'MA0496.4', 'MA1101.3', 'MA1470.2', 'MA0877.4', 'MA0635.2',
       'MA0875.2', 'MA1471.2', 'MA1634.2', 'MA0462.3', 'MA0488.2',
       'MA0835.3', 'MA0463.3', 'MA1635.2', 'MA0817.2', 'MA0464.3',
       'MA1928.2', 'MA0876.2', 'MA0465.3', 'MA1473.2', 'MA0102.5',
       'MA0466.4', 'MA0836.3', 'MA0837.3', 'MA1636.2', 'MA0819.3',
       'MA0018.5', 'MA0638.2', 'MA0839.2', 'MA1474.2', 'MA1475.2',
       'MA0609.3', 'MA0139.2', 'MA1929.2', 'MA1930.2', 'MA1102.3',
       'MA0754.3', 'MA0901.3', 'MA0755.2', 'MA0639.2', 'MA0879.3',
       'MA0882.2', 'MA0610.2', 'MA1707.2', 'MA1478.2', 'MA1479.2',
       'MA1480.2', 'MA1481.2', 'MA0864.3', 'MA0469.4', 'MA0756.3',
       'MA0470.3', 'MA0471.3', 'MA0865.3', 'MA0154.5', 'MA1637.2',
       'MA0162.5', 'MA0732.2', 'MA0733.2', 'MA0598.4', 'MA0473.4',
       'MA1483.3', 'MA0640.3', 'MA0028.3', 'MA0800.2', 'MA1708.2',
       'MA1495.2', 'MA1932.2', 'MA0779.2', 'MA0014.4', 'MA0781.2',
       'MA0686.2', 'MA1933.2', 'MA0828.3', 'MA0843.2', 'MA0759.3',
       'MA0076.3', 'MA0612.3', 'MA0886.2', 'MA0027.3', 'MA0642.3',
       'MA0760.2', 'MA1934.2', 'MA0820.2', 'MA1935.2', 'MA1936.2',
       'MA1937.2', 'MA0058.4', 'MA1938.2', 'MA0048.3', 'MA1939.2',
       'MA0112.4', 'MA0592.4', 'MA0141.4', 'MA0644.3', 'MA0098.4',
       'MA1484.2', 'MA0761.3', 'MA0762.2', 'MA1940.2', 'MA1941.2',
       'MA1942.2', 'MA1943.2', 'MA0763.2', 'MA0764.4', 'MA0765.4',
       'MA1944.2', 'MA1945.2', 'MA1946.2', 'MA1947.2', 'MA1948.2',
       'MA0900.3', 'MA0645.2', 'MA0887.2', 'MA0888.2', 'MA0156.4',
       'MA0475.3', 'MA1949.2', 'MA1950.2', 'MA0476.2', 'MA1951.2',
       'MA0099.4', 'MA1126.2', 'MA1134.2', 'MA1140.3', 'MA0490.3',
       'MA1141.2', 'MA0492.2', 'MA0491.3', 'MA1135.2', 'MA0477.3',
       'MA1128.2', 'MA1137.2', 'MA1142.2', 'MA1143.2', 'MA0478.2',
       'MA1130.2', 'MA1131.2', 'MA1138.2', 'MA1139.2', 'MA1144.2',
       'MA1145.2', 'MA0148.5', 'MA0047.4', 'MA1683.2', 'MA0846.2',
       'MA0031.2', 'MA0847.4', 'MA0041.3', 'MA1487.3', 'MA0030.2',
       'MA0479.2', 'MA1952.2', 'MA0682.3', 'MA0852.3', 'MA1103.3',
       'MA1953.2', 'MA1954.2', 'MA1955.2', 'MA1956.2', 'MA0481.4',
       'MA0593.2', 'MA0062.4', 'MA0035.5', 'MA0140.3', 'MA0036.4',
       'MA0482.3', 'MA0766.3', 'MA1104.3', 'MA0889.2', 'MA0890.2',
       'MA0646.2', 'MA0143.5', 'MA0767.2', 'MA0038.3', 'MA1491.3',
       'MA0735.2', 'MA0647.2', 'MA1105.3', 'MA0648.2', 'MA0891.2',
       'MA0892.2', 'MA0893.3', 'MA0522.4', 'MA1638.2', 'MA1099.3',
       'MA0616.3', 'MA0894.2', 'MA0649.2', 'MA0738.2', 'MA1106.2',
       'MA0131.3', 'MA0043.4', 'MA0895.2', 'MA0046.3', 'MA1494.2',
       'MA0114.5', 'MA0484.3', 'MA0899.2', 'MA1496.2', 'MA1497.2',
       'MA1498.3', 'MA0594.3', 'MA0902.3', 'MA1566.3', 'MA0903.2',
       'MA1499.2', 'MA0904.3', 'MA1500.2', 'MA1501.2', 'MA1502.2',
       'MA1503.2', 'MA0905.2', 'MA0651.3', 'MA0906.2', 'MA0907.2',
       'MA1504.2', 'MA1505.2', 'MA0485.3', 'MA1506.2', 'MA0908.2',
       'MA0873.2', 'MA1958.2', 'MA1507.2', 'MA0910.3', 'MA0913.3',
       'MA1508.2', 'MA0051.2', 'MA1418.2', 'MA1419.2', 'MA0772.2',
       'MA0652.2', 'MA0914.2', 'MA0654.2', 'MA0656.2', 'MA1132.2',
       'MA1133.2', 'MA0493.3', 'MA1512.2', 'MA0657.2', 'MA1513.2',
       'MA1514.2', 'MA1515.2', 'MA1516.2', 'MA0039.5', 'MA1517.2',
       'MA1959.2', 'MA1107.3', 'MA0618.2', 'MA0699.2', 'MA0700.3',
       'MA1519.2', 'MA0658.2', 'MA0701.3', 'MA0702.3', 'MA0703.3',
       'MA1520.2', 'MA0501.2', 'MA0841.2', 'MA1521.2', 'MA0495.4',
       'MA0089.3', 'MA0059.2', 'MA0147.4', 'MA1522.2', 'MA0052.5',
       'MA0497.2', 'MA0498.3', 'MA1639.2', 'MA1640.2', 'MA0775.2',
       'MA0661.2', 'MA0706.2', 'MA1960.2', 'MA0620.4', 'MA0662.2',
       'MA0664.2', 'MA0825.2', 'MA0707.3', 'MA1523.2', 'MA0666.3',
       'MA0708.3', 'MA1108.3', 'MA0100.4', 'MA0104.5', 'MA1641.2',
       'MA0499.3', 'MA0500.3', 'MA0056.3', 'MA1109.2', 'MA1642.2',
       'MA0625.3', 'MA1525.3', 'MA0670.2', 'MA1643.2', 'MA0161.3',
       'MA1527.2', 'MA0025.3', 'MA0671.2', 'MA1528.2', 'MA0778.2',
       'MA0060.4', 'MA0502.3', 'MA1644.2', 'MA1529.2', 'MA1645.2',
       'MA0672.2', 'MA2003.2', 'MA0063.3', 'MA0673.2', 'MA0674.2',
       'MA0675.2', 'MA1530.2', 'MA0710.2', 'MA1531.2', 'MA1146.2',
       'MA1533.2', 'MA1534.2', 'MA1535.2', 'MA0504.2', 'MA1536.2',
       'MA0017.3', 'MA1537.2', 'MA1111.2', 'MA0113.4', 'MA0727.2',
       'MA1112.3', 'MA0160.3', 'MA1147.2', 'MA1541.2', 'MA0842.3',
       'MA0679.3', 'MA0757.2', 'MA1542.2', 'MA1646.2', 'MA0711.2',
       'MA0712.3', 'MA1544.2', 'MA1545.2', 'MA1961.2', 'MA0067.3',
       'MA1546.2', 'MA0070.2', 'MA1113.3', 'MA1114.2', 'MA0132.3',
       'MA0681.3', 'MA0714.2', 'MA0782.3', 'MA1548.2', 'MA0784.3',
       'MA0785.2', 'MA0507.3', 'MA0627.3', 'MA0786.2', 'MA0790.2',
       'MA0683.2', 'MA0791.2', 'MA1115.2', 'MA0628.2', 'MA1549.2',
       'MA0793.2', 'MA1148.2', 'MA1550.2', 'MA0066.2', 'MA0508.4',
       'MA1723.2', 'MA0716.2', 'MA0075.4', 'MA1149.2', 'MA1552.2',
       'MA1553.2', 'MA0718.2', 'MA0717.2', 'MA1116.2', 'MA1117.2',
       'MA0138.3', 'MA0600.3', 'MA0799.3', 'MA0510.3', 'MA1554.2',
       'MA0719.2', 'MA0072.2', 'MA1150.2', 'MA1151.2', 'MA0073.2',
       'MA0684.3', 'MA1963.2', 'MA0743.3', 'MA0744.3', 'MA0630.2',
       'MA1118.2', 'MA1119.2', 'MA1964.2', 'MA1558.2', 'MA0745.3',
       'MA1559.2', 'MA1560.2', 'MA0442.3', 'MA1561.2', 'MA1120.2',
       'MA1562.2', 'MA1152.2', 'MA0867.3', 'MA0868.3', 'MA0077.2',
       'MA0746.3', 'MA1965.2', 'MA0747.2', 'MA1564.2', 'MA0081.3',
       'MA0687.2', 'MA0829.3', 'MA0084.2', 'MA0137.4', 'MA0517.2',
       'MA0144.3', 'MA0091.2', 'MA0802.2', 'MA1565.2', 'MA0804.2',
       'MA0688.2', 'MA1648.2', 'MA1568.2', 'MA0830.3', 'MA0769.3',
       'MA0523.2', 'MA0632.3', 'MA0090.4', 'MA1121.2', 'MA0809.3',
       'MA0810.2', 'MA0003.5', 'MA0811.2', 'MA0812.2', 'MA0524.3',
       'MA0814.3', 'MA1569.2', 'MA1966.2', 'MA1967.2', 'MA1968.2',
       'MA1122.2', 'MA0692.2', 'MA0871.3', 'MA0597.3', 'MA1969.2',
       'MA1574.2', 'MA1575.2', 'MA1576.2', 'MA1577.2', 'MA0861.2',
       'MA1970.2', 'MA1123.3', 'MA0721.2', 'MA0093.4', 'MA0526.5',
       'MA0722.2', 'MA0723.3', 'MA1578.2', 'MA0725.2', 'MA0726.2',
       'MA0844.2', 'MA0748.3', 'MA0749.2', 'MA1971.2', 'MA1649.2',
       'MA1650.2', 'MA0698.2', 'MA1579.2', 'MA0527.2', 'MA1581.2',
       'MA0750.3', 'MA0694.2', 'MA0695.2', 'MA0103.4', 'MA1651.2',
       'MA1583.2', 'MA0751.2', 'MA1584.2', 'MA1709.2', 'MA1585.2',
       'MA1973.2', 'MA1652.2', 'MA1589.2', 'MA1653.2', 'MA1654.2',
       'MA1725.2', 'MA1974.2', 'MA1975.2', 'MA1710.2', 'MA0528.3',
       'MA1592.2', 'MA1630.3', 'MA1154.2', 'MA1593.2', 'MA1976.2',
       'MA1977.2', 'MA1726.2', 'MA1655.2', 'MA1711.2', 'MA1978.2',
       'MA1125.2', 'MA0752.2', 'MA1979.2', 'MA1727.2', 'MA1656.2',
       'MA1712.2', 'MA1981.2', 'MA1728.2', 'MA1982.2', 'MA1983.2',
       'MA1713.2', 'MA1657.2', 'MA1984.2', 'MA1714.2', 'MA1729.2',
       'MA1599.2', 'MA1600.2', 'MA1986.2', 'MA1987.2', 'MA1730.2',
       'MA0753.3', 'MA1716.2', 'MA1731.2', 'MA1717.2', 'MA1719.2',
       'MA1720.2', 'MA1721.2', 'MA1602.2', 'MA1722.2'], dtype=object)

In [29]:
tmp.uns["chromvar_gearyC"]

,TF,motif_id,C,pval_norm,var_norm,pval_z_sim,pval_sim,var_sim,pval_norm_fdr_bh,pval_z_sim_fdr_bh,pval_sim_fdr_bh
179,ALX3,MA0634.2,1.001934,4.481267e-01,0.00022,1.973358e-01,0.195804,0.000121,4.544473e-01,2.127202e-01,0.211069
181,ARGFX,MA1463.2,0.974412,4.221382e-02,0.00022,1.418033e-02,0.016983,0.000127,5.488560e-02,1.877653e-02,0.022081
182,ARNT,MA0259.2,0.912653,1.928600e-09,0.00022,4.261837e-14,0.000999,0.000156,6.540864e-09,1.692962e-13,0.001596
183,ARNT2,MA1464.2,0.944716,9.648080e-05,0.00022,9.055137e-06,0.000999,0.000143,2.057122e-04,1.764402e-05,0.001596
184,ASCL1,MA1100.3,0.921212,5.390709e-08,0.00022,1.901183e-10,0.000999,0.000161,1.642339e-07,5.866739e-10,0.001596
...,...,...,...,...,...,...,...,...,...,...,...
132,ZSCAN16,MA2100.1,0.823790,7.281035e-33,0.00022,7.534015e-36,0.000999,0.000195,6.543830e-32,7.035008e-35,0.001596
177,ZSCAN21,MA2336.1,0.958102,2.361272e-03,0.00022,1.946054e-04,0.000999,0.000138,3.876152e-03,3.299775e-04,0.001596
718,ZSCAN29,MA1602.2,0.975615,5.004830e-02,0.00022,1.248996e-02,0.015984,0.000130,6.414390e-02,1.672306e-02,0.021010
719,ZSCAN31,MA1722.2,0.945155,1.084487e-04,0.00022,3.875070e-06,0.000999,0.000142,2.276752e-04,8.194633e-06,0.001596
96,ZSCAN4,MA1155.1,0.764528,4.427721e-57,0.00022,4.515657e-54,0.000999,0.000224,7.403561e-56,7.918920e-53,0.001596

### mapping between TFs and Motifs

In [2]:
# read mapping
import pandas as pd
motif_map = pd.read_csv("/nfs/home/students/m.back/swarm/backend/uploads/job_1765704415143_ff39eb2f-8a8f-4650-b124-1ee2777994f7/kackhaufen1/motif_to_tf.csv")

In [4]:
motif_map["motif_id"].nunique()

720

In [19]:
motif_map["TF"].str.split("::").str.len().value_counts()#nunique()

TF
1    653
2     67
Name: count, dtype: int64

In [28]:
motif_map_merit = motif_map.copy()
motif_map_merit["TF"] = motif_map["TF"].str.split("::")

In [41]:
tf_to_motifs = (
    motif_map_merit.explode("TF")                      # one row per (motif_id, TF)
      .dropna(subset=["TF"])              # in case any TF lists are empty/NaN
      .groupby("TF")["motif_id"]
      .apply(list)
      .to_dict()
)

In [45]:
len(tf_to_motifs.keys())

630

In [ ]:
# motifs per TF
motifs_per_tf = (
    motif_map_merit.explode("TF")
      .dropna(subset=["TF"])
      .groupby("TF")["motif_id"]
      .nunique()              # motifs are unique, but nunique is safe
      .sort_values(ascending=False)
)

# Series: index=TF, value=#motifs
print(motifs_per_tf.describe())

count    630.000000
mean       1.249206
std        0.970040
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max       11.000000
Name: motif_id, dtype: float64

In [55]:
count_distribution = (
    motifs_per_tf
        .value_counts()
        .sort_index()
)
count_distribution

motif_id
1     561
2      39
3      10
4       6
5       3
6       5
7       4
10      1
11      1
Name: count, dtype: int64

In [69]:
motif_map_merit_exp = (
    motif_map_merit.explode("TF")                      # one row per (motif_id, TF)
      .dropna(subset=["TF"])              # in case any TF lists are empty/NaN
     # .groupby("TF")["motif_id"]
)

In [57]:
adata_ch_m_g = ad.read_h5ad("/nfs/home/students/m.back/swarm/backend/uploads/job_1765704415143_ff39eb2f-8a8f-4650-b124-1ee2777994f7/kackhaufen1/adata_tg_scores_w_chromvar.h5ad")

In [58]:
adata_ch_m_g

AnnData object with n_obs × n_vars = 1448 × 2000
    obs: 'in_tissue', 'array_row', 'array_col', 'suspension_type', 'assay_ontology_term_id', 'Sample_ID', 'organism_ontology_term_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'pathologist_annotation', 'B-cells', 'CAFs', 'Cancer Epithelial', 'Endothelial', 'Myeloid', 'Normal Epithelial', 'PVL', 'T-cells', 'stereoscope_annotation', 'cell_type_ontology_term_id', 'is_primary_data', 'treatment', 'donor_id', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'leiden', 'uniform_density', 'rna_count_based_density'
    var: 'vf_vst_counts_mean', 'vf_vst_counts_variance', 'vf_vst_counts_variance.expected', 'vf_vst_counts_variance.standardized', 'vf_vst_counts_variable', 'vf_vst_counts_rank', 'var.features', 'var.features.rank', 'n_cells', 'sparsity', 'is_training'
    uns: 'chromvar_gearyC', 'chromvar_moranI', 'chromvar_motifs', 'neighbors', 'overlap_genes', 'spatial', 'training_genes'
    obsm: 'chromvar_spot_scores', 'spatial', 'tangram_ct_pred'

In [65]:
adata_ch_m_g.uns["chromvar_moranI"]

,I,pval_norm,var_norm,pval_z_sim,pval_sim,var_sim,pval_norm_fdr_bh,pval_z_sim_fdr_bh,pval_sim_fdr_bh
MA0820.2,0.425674,0.000000,0.00022,0.000000,0.000999,0.000323,0.000000,0.000000,0.001710
MA0103.4,0.425674,0.000000,0.00022,0.000000,0.000999,0.000323,0.000000,0.000000,0.001710
MA1631.2,0.410118,0.000000,0.00022,0.000000,0.000999,0.000320,0.000000,0.000000,0.001710
MA1643.2,0.392089,0.000000,0.00022,0.000000,0.000999,0.000313,0.000000,0.000000,0.001710
MA0524.3,0.382031,0.000000,0.00022,0.000000,0.000999,0.000313,0.000000,0.000000,0.001710
...,...,...,...,...,...,...,...,...,...
MA1537.2,-0.012069,0.442923,0.00022,0.123632,0.121878,0.000115,0.477225,0.139547,0.137784
MA0158.2,-0.012628,0.420842,0.00022,0.104079,0.103896,0.000114,0.455701,0.118972,0.118762
MA2003.2,-0.013527,0.386725,0.00022,0.103502,0.096903,0.000114,0.435278,0.118500,0.111122
MA0779.2,-0.014068,0.367009,0.00022,0.078662,0.075924,0.000100,0.416214,0.091076,0.088332
MA0673.2,-0.020460,0.182506,0.00022,0.021046,0.017982,0.000104,0.221658,0.026707,0.023046

In [79]:
motif_map_merit = motif_map.copy()
motif_map_merit["TF"] = motif_map["TF"].str.split("::")
motif_map_merit_exp = (
    motif_map_merit.explode("TF")                      # one row per (motif_id, TF)
      .dropna(subset=["TF"])              # in case any TF lists are empty/NaN
)

In [ ]:

motif_map_merit_exp

     motif_id       TF
0    MA0069.1     PAX6
1    MA0071.1     RORA
2    MA0074.1     RXRA
2    MA0074.1      VDR
3    MA0101.1      REL
..        ...      ...
715  MA1719.2   ZNF816
716  MA1720.2    ZNF85
717  MA1721.2    ZNF93
718  MA1602.2  ZSCAN29
719  MA1722.2  ZSCAN31

[787 rows x 2 columns]

In [83]:
merge = adata_ch_m_g.uns["chromvar_moranI"].merge(motif_map_merit_exp, left_index=True, right_on="motif_id")
# order columns
merge = merge[["TF", "motif_id", "I", "pval_norm", "var_norm", "pval_z_sim", "pval_sim", "var_sim", "pval_norm_fdr_bh","pval_z_sim_fdr_bh", "pval_sim_fdr_bh"]]
merge = merge.sort_values(by="TF")

In [84]:
merge

,TF,motif_id,I,pval_norm,var_norm,pval_z_sim,pval_sim,var_sim,pval_norm_fdr_bh,pval_z_sim_fdr_bh,pval_sim_fdr_bh
179,ALX3,MA0634.2,0.011465,0.412372,0.00022,1.556831e-01,0.161838,0.000129,0.448556,1.683251e-01,0.174194
181,ARGFX,MA1463.2,0.028950,0.045625,0.00022,7.070644e-03,0.011988,0.000136,0.064703,9.890648e-03,0.016171
182,ARNT,MA0259.2,0.049368,0.000736,0.00022,1.409178e-05,0.000999,0.000140,0.001504,2.862143e-05,0.001710
183,ARNT2,MA1464.2,0.038132,0.008845,0.00022,5.531100e-04,0.001998,0.000139,0.014721,9.017825e-04,0.003137
184,ASCL1,MA1100.3,0.069567,0.000002,0.00022,6.933394e-09,0.000999,0.000152,0.000007,2.186452e-08,0.001710
...,...,...,...,...,...,...,...,...,...,...,...
132,ZSCAN16,MA2100.1,0.162174,0.000000,0.00022,0.000000e+00,0.000999,0.000193,0.000000,0.000000e+00,0.001710
177,ZSCAN21,MA2336.1,0.042851,0.003322,0.00022,1.021245e-04,0.000999,0.000134,0.006078,1.858924e-04,0.001710
718,ZSCAN29,MA1602.2,0.064415,0.000011,0.00022,3.122484e-08,0.000999,0.000140,0.000032,8.769788e-08,0.001710
719,ZSCAN31,MA1722.2,0.055781,0.000140,0.00022,1.686562e-06,0.000999,0.000143,0.000321,3.949961e-06,0.001710
96,ZSCAN4,MA1155.1,0.228452,0.000000,0.00022,0.000000e+00,0.000999,0.000238,0.000000,0.000000e+00,0.001710

In [4]:
adata_ch_m_g.uns["chromvar_moranI"]

,I,pval_norm,var_norm,pval_z_sim,pval_sim,var_sim,pval_norm_fdr_bh,pval_z_sim_fdr_bh,pval_sim_fdr_bh
MA0820.2,0.425674,0.000000,0.00022,0.000000,0.000999,0.000323,0.000000,0.000000,0.001710
MA0103.4,0.425674,0.000000,0.00022,0.000000,0.000999,0.000323,0.000000,0.000000,0.001710
MA1631.2,0.410118,0.000000,0.00022,0.000000,0.000999,0.000320,0.000000,0.000000,0.001710
MA1643.2,0.392089,0.000000,0.00022,0.000000,0.000999,0.000313,0.000000,0.000000,0.001710
MA0524.3,0.382031,0.000000,0.00022,0.000000,0.000999,0.000313,0.000000,0.000000,0.001710
...,...,...,...,...,...,...,...,...,...
MA1537.2,-0.012069,0.442923,0.00022,0.123632,0.121878,0.000115,0.477225,0.139547,0.137784
MA0158.2,-0.012628,0.420842,0.00022,0.104079,0.103896,0.000114,0.455701,0.118972,0.118762
MA2003.2,-0.013527,0.386725,0.00022,0.103502,0.096903,0.000114,0.435278,0.118500,0.111122
MA0779.2,-0.014068,0.367009,0.00022,0.078662,0.075924,0.000100,0.416214,0.091076,0.088332
MA0673.2,-0.020460,0.182506,0.00022,0.021046,0.017982,0.000104,0.221658,0.026707,0.023046

In [8]:
adata_ch_m_g#.obsm#["chromvar_spot_scores"]

AnnData object with n_obs × n_vars = 1448 × 2000
    obs: 'in_tissue', 'array_row', 'array_col', 'suspension_type', 'assay_ontology_term_id', 'Sample_ID', 'organism_ontology_term_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'pathologist_annotation', 'B-cells', 'CAFs', 'Cancer Epithelial', 'Endothelial', 'Myeloid', 'Normal Epithelial', 'PVL', 'T-cells', 'stereoscope_annotation', 'cell_type_ontology_term_id', 'is_primary_data', 'treatment', 'donor_id', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'leiden', 'uniform_density', 'rna_count_based_density'
    var: 'vf_vst_counts_mean', 'vf_vst_counts_variance', 'vf_vst_counts_variance.expected', 'vf_vst_counts_variance.standardized', 'vf_vst_counts_variable', 'vf_vst_counts_rank', 'var.features', 'var.features.rank', 'n_cells', 'sparsity', 'is_training'
    uns: 'chromvar_gearyC', 'chromvar_moranI', 'chromvar_motifs', 'neighbors', 'overlap_genes', 'spatial', 'training_genes'
    obsm: 'chromvar_spot_scores', 'spatial', 'tangram_ct_pred'

In [9]:
adata = ad.read_h5ad("/workspaces/swarm/backend/uploads/job_1765704415143_ff39eb2f-8a8f-4650-b124-1ee2777994f7/kackhaufen1/adata_tg_scores.h5ad")

In [15]:
adata.obsm["chromvar_spot_scores"].shape

(1448, 719)

In [11]:
adata.uns["chromvar_motifs"]

array(['MA0071.1', 'MA0074.1', 'MA0101.1', 'MA0107.1', 'MA0115.1',
       'MA0119.1', 'MA0130.1', 'MA0149.1', 'MA0155.1', 'MA0159.1',
       'MA0163.1', 'MA0468.1', 'MA0258.2', 'MA0595.1', 'MA0596.1',
       'MA0599.1', 'MA0613.1', 'MA0636.1', 'MA0641.1', 'MA0042.2',
       'MA0033.2', 'MA0153.2', 'MA0486.2', 'MA0653.1', 'MA0655.1',
       'MA0660.1', 'MA0663.1', 'MA0665.1', 'MA0667.1', 'MA0669.1',
       'MA0678.1', 'MA0068.2', 'MA0083.3', 'MA0009.2', 'MA0689.1',
       'MA0691.1', 'MA0696.1', 'MA0713.1', 'MA0715.1', 'MA0724.1',
       'MA0729.1', 'MA0730.1', 'MA0731.1', 'MA0472.2', 'MA0736.1',
       'MA0737.1', 'MA0741.1', 'MA0088.2', 'MA0758.1', 'MA0770.1',
       'MA0771.1', 'MA0773.1', 'MA0774.1', 'MA0776.1', 'MA0777.1',
       'MA0105.4', 'MA0780.1', 'MA0783.1', 'MA0787.1', 'MA0788.1',
       'MA0789.1', 'MA0792.1', 'MA0794.1', 'MA0795.1', 'MA0796.1',
       'MA0797.1', 'MA0511.2', 'MA0801.1', 'MA0803.1', 'MA0805.1',
       'MA0806.1', 'MA0807.1', 'MA0808.1', 'MA0813.1', 'MA0815.1',
       'MA0822.1', 'MA0823.1', 'MA0826.1', 'MA0827.1', 'MA0838.1',
       'MA0845.1', 'MA0032.2', 'MA0848.1', 'MA0849.1', 'MA0850.1',
       'MA0855.1', 'MA0856.1', 'MA0525.2', 'MA0106.3', 'MA0862.1',
       'MA0863.1', 'MA0024.3', 'MA0866.1', 'MA0872.1', 'MA1124.1',
       'MA1155.1', 'MA1127.1', 'MA1129.1', 'MA1136.1', 'MA1420.1',
       'MA1421.1', 'MA1468.1', 'MA1485.1', 'MA1489.1', 'MA1493.1',
       'MA1509.1', 'MA1538.1', 'MA1539.1', 'MA1555.1', 'MA1556.1',
       'MA1557.1', 'MA1570.1', 'MA1571.1', 'MA1572.1', 'MA1580.1',
       'MA1587.1', 'MA1588.1', 'MA1594.1', 'MA1596.1', 'MA1597.1',
       'MA0158.2', 'MA0912.2', 'MA0623.2', 'MA2093.1', 'MA2094.1',
       'MA2096.1', 'MA1715.1', 'MA2097.1', 'MA2098.1', 'MA2099.1',
       'MA1718.1', 'MA2100.1', 'MA2101.1', 'MA2102.1', 'MA1931.1',
       'MA1957.1', 'MA1962.1', 'MA1972.1', 'MA1980.1', 'MA1985.1',
       'MA2117.1', 'MA2118.1', 'MA2119.1', 'MA2120.1', 'MA2121.1',
       'MA0079.5', 'MA0509.3', 'MA0516.3', 'MA0607.2', 'MA0685.2',
       'MA0740.2', 'MA0742.2', 'MA0798.3', 'MA0818.2', 'MA0821.2',
       'MA0831.3', 'MA0878.3', 'MA0884.2', 'MA1511.2', 'MA1532.2',
       'MA1547.2', 'MA1563.2', 'MA1601.2', 'MA1633.2', 'MA2324.1',
       'MA2325.1', 'MA2326.1', 'MA2327.1', 'MA2328.1', 'MA2329.1',
       'MA2330.1', 'MA2331.1', 'MA2332.1', 'MA2333.1', 'MA2334.1',
       'MA2335.1', 'MA2336.1', 'MA2341.1', 'MA0634.2', 'MA0690.3',
       'MA1463.2', 'MA0259.2', 'MA1464.2', 'MA1100.3', 'MA1631.2',
       'MA1632.2', 'MA0605.3', 'MA0833.3', 'MA1466.2', 'MA0834.2',
       'MA0496.4', 'MA1101.3', 'MA1470.2', 'MA0877.4', 'MA0635.2',
       'MA0875.2', 'MA1471.2', 'MA1634.2', 'MA0462.3', 'MA0488.2',
       'MA0835.3', 'MA0463.3', 'MA1635.2', 'MA0817.2', 'MA0464.3',
       'MA1928.2', 'MA0876.2', 'MA0465.3', 'MA1473.2', 'MA0102.5',
       'MA0466.4', 'MA0836.3', 'MA0837.3', 'MA1636.2', 'MA0819.3',
       'MA0018.5', 'MA0638.2', 'MA0839.2', 'MA1474.2', 'MA1475.2',
       'MA0609.3', 'MA0139.2', 'MA1929.2', 'MA1930.2', 'MA1102.3',
       'MA0754.3', 'MA0901.3', 'MA0755.2', 'MA0639.2', 'MA0879.3',
       'MA0882.2', 'MA0610.2', 'MA1707.2', 'MA1478.2', 'MA1479.2',
       'MA1480.2', 'MA1481.2', 'MA0864.3', 'MA0469.4', 'MA0756.3',
       'MA0470.3', 'MA0471.3', 'MA0865.3', 'MA0154.5', 'MA1637.2',
       'MA0162.5', 'MA0732.2', 'MA0733.2', 'MA0598.4', 'MA0473.4',
       'MA1483.3', 'MA0640.3', 'MA0028.3', 'MA0800.2', 'MA1708.2',
       'MA1495.2', 'MA1932.2', 'MA0779.2', 'MA0014.4', 'MA0781.2',
       'MA0686.2', 'MA1933.2', 'MA0828.3', 'MA0843.2', 'MA0759.3',
       'MA0076.3', 'MA0612.3', 'MA0886.2', 'MA0027.3', 'MA0642.3',
       'MA0760.2', 'MA1934.2', 'MA0820.2', 'MA1935.2', 'MA1936.2',
       'MA1937.2', 'MA0058.4', 'MA1938.2', 'MA0048.3', 'MA1939.2',
       'MA0112.4', 'MA0592.4', 'MA0141.4', 'MA0644.3', 'MA0098.4',
       'MA1484.2', 'MA0761.3', 'MA0762.2', 'MA1940.2', 'MA1941.2',
       'MA1942.2', 'MA1943.2', 'MA0763.2', 'MA0764.4', 'MA0765.4',
       'MA1944.2', 'MA1945.2', 'MA1946.2', 'MA1947.2', 'MA1948.2',
       'MA0900.3', 'MA0645.2', 'MA0887.2', 'MA0888.2', 'MA0156.4',
       'MA0475.3', 'MA1949.2', 'MA1950.2', 'MA0476.2', 'MA1951.2',
       'MA0099.4', 'MA1126.2', 'MA1134.2', 'MA1140.3', 'MA0490.3',
       'MA1141.2', 'MA0492.2', 'MA0491.3', 'MA1135.2', 'MA0477.3',
       'MA1128.2', 'MA1137.2', 'MA1142.2', 'MA1143.2', 'MA0478.2',
       'MA1130.2', 'MA1131.2', 'MA1138.2', 'MA1139.2', 'MA1144.2',
       'MA1145.2', 'MA0148.5', 'MA0047.4', 'MA1683.2', 'MA0846.2',
       'MA0031.2', 'MA0847.4', 'MA0041.3', 'MA1487.3', 'MA0030.2',
       'MA0479.2', 'MA1952.2', 'MA0682.3', 'MA0852.3', 'MA1103.3',
       'MA1953.2', 'MA1954.2', 'MA1955.2', 'MA1956.2', 'MA0481.4',
       'MA0593.2', 'MA0062.4', 'MA0035.5', 'MA0140.3', 'MA0036.4',
       'MA0482.3', 'MA0766.3', 'MA1104.3', 'MA0889.2', 'MA0890.2',
       'MA0646.2', 'MA0143.5', 'MA0767.2', 'MA0038.3', 'MA1491.3',
       'MA0735.2', 'MA0647.2', 'MA1105.3', 'MA0648.2', 'MA0891.2',
       'MA0892.2', 'MA0893.3', 'MA0522.4', 'MA1638.2', 'MA1099.3',
       'MA0616.3', 'MA0894.2', 'MA0649.2', 'MA0738.2', 'MA1106.2',
       'MA0131.3', 'MA0043.4', 'MA0895.2', 'MA0046.3', 'MA1494.2',
       'MA0114.5', 'MA0484.3', 'MA0899.2', 'MA1496.2', 'MA1497.2',
       'MA1498.3', 'MA0594.3', 'MA0902.3', 'MA1566.3', 'MA0903.2',
       'MA1499.2', 'MA0904.3', 'MA1500.2', 'MA1501.2', 'MA1502.2',
       'MA1503.2', 'MA0905.2', 'MA0651.3', 'MA0906.2', 'MA0907.2',
       'MA1504.2', 'MA1505.2', 'MA0485.3', 'MA1506.2', 'MA0908.2',
       'MA0873.2', 'MA1958.2', 'MA1507.2', 'MA0910.3', 'MA0913.3',
       'MA1508.2', 'MA0051.2', 'MA1418.2', 'MA1419.2', 'MA0772.2',
       'MA0652.2', 'MA0914.2', 'MA0654.2', 'MA0656.2', 'MA1132.2',
       'MA1133.2', 'MA0493.3', 'MA1512.2', 'MA0657.2', 'MA1513.2',
       'MA1514.2', 'MA1515.2', 'MA1516.2', 'MA0039.5', 'MA1517.2',
       'MA1959.2', 'MA1107.3', 'MA0618.2', 'MA0699.2', 'MA0700.3',
       'MA1519.2', 'MA0658.2', 'MA0701.3', 'MA0702.3', 'MA0703.3',
       'MA1520.2', 'MA0501.2', 'MA0841.2', 'MA1521.2', 'MA0495.4',
       'MA0089.3', 'MA0059.2', 'MA0147.4', 'MA1522.2', 'MA0052.5',
       'MA0497.2', 'MA0498.3', 'MA1639.2', 'MA1640.2', 'MA0775.2',
       'MA0661.2', 'MA0706.2', 'MA1960.2', 'MA0620.4', 'MA0662.2',
       'MA0664.2', 'MA0825.2', 'MA0707.3', 'MA1523.2', 'MA0666.3',
       'MA0708.3', 'MA1108.3', 'MA0100.4', 'MA0104.5', 'MA1641.2',
       'MA0499.3', 'MA0500.3', 'MA0056.3', 'MA1109.2', 'MA1642.2',
       'MA0625.3', 'MA1525.3', 'MA0670.2', 'MA1643.2', 'MA0161.3',
       'MA1527.2', 'MA0025.3', 'MA0671.2', 'MA1528.2', 'MA0778.2',
       'MA0060.4', 'MA0502.3', 'MA1644.2', 'MA1529.2', 'MA1645.2',
       'MA0672.2', 'MA2003.2', 'MA0063.3', 'MA0673.2', 'MA0674.2',
       'MA0675.2', 'MA1530.2', 'MA0710.2', 'MA1531.2', 'MA1146.2',
       'MA1533.2', 'MA1534.2', 'MA1535.2', 'MA0504.2', 'MA1536.2',
       'MA0017.3', 'MA1537.2', 'MA1111.2', 'MA0113.4', 'MA0727.2',
       'MA1112.3', 'MA0160.3', 'MA1147.2', 'MA1541.2', 'MA0842.3',
       'MA0679.3', 'MA0757.2', 'MA1542.2', 'MA1646.2', 'MA0711.2',
       'MA0712.3', 'MA1544.2', 'MA1545.2', 'MA1961.2', 'MA0067.3',
       'MA1546.2', 'MA0070.2', 'MA1113.3', 'MA1114.2', 'MA0132.3',
       'MA0681.3', 'MA0714.2', 'MA0782.3', 'MA1548.2', 'MA0784.3',
       'MA0785.2', 'MA0507.3', 'MA0627.3', 'MA0786.2', 'MA0790.2',
       'MA0683.2', 'MA0791.2', 'MA1115.2', 'MA0628.2', 'MA1549.2',
       'MA0793.2', 'MA1148.2', 'MA1550.2', 'MA0066.2', 'MA0508.4',
       'MA1723.2', 'MA0716.2', 'MA0075.4', 'MA1149.2', 'MA1552.2',
       'MA1553.2', 'MA0718.2', 'MA0717.2', 'MA1116.2', 'MA1117.2',
       'MA0138.3', 'MA0600.3', 'MA0799.3', 'MA0510.3', 'MA1554.2',
       'MA0719.2', 'MA0072.2', 'MA1150.2', 'MA1151.2', 'MA0073.2',
       'MA0684.3', 'MA1963.2', 'MA0743.3', 'MA0744.3', 'MA0630.2',
       'MA1118.2', 'MA1119.2', 'MA1964.2', 'MA1558.2', 'MA0745.3',
       'MA1559.2', 'MA1560.2', 'MA0442.3', 'MA1561.2', 'MA1120.2',
       'MA1562.2', 'MA1152.2', 'MA0867.3', 'MA0868.3', 'MA0077.2',
       'MA0746.3', 'MA1965.2', 'MA0747.2', 'MA1564.2', 'MA0081.3',
       'MA0687.2', 'MA0829.3', 'MA0084.2', 'MA0137.4', 'MA0517.2',
       'MA0144.3', 'MA0091.2', 'MA0802.2', 'MA1565.2', 'MA0804.2',
       'MA0688.2', 'MA1648.2', 'MA1568.2', 'MA0830.3', 'MA0769.3',
       'MA0523.2', 'MA0632.3', 'MA0090.4', 'MA1121.2', 'MA0809.3',
       'MA0810.2', 'MA0003.5', 'MA0811.2', 'MA0812.2', 'MA0524.3',
       'MA0814.3', 'MA1569.2', 'MA1966.2', 'MA1967.2', 'MA1968.2',
       'MA1122.2', 'MA0692.2', 'MA0871.3', 'MA0597.3', 'MA1969.2',
       'MA1574.2', 'MA1575.2', 'MA1576.2', 'MA1577.2', 'MA0861.2',
       'MA1970.2', 'MA1123.3', 'MA0721.2', 'MA0093.4', 'MA0526.5',
       'MA0722.2', 'MA0723.3', 'MA1578.2', 'MA0725.2', 'MA0726.2',
       'MA0844.2', 'MA0748.3', 'MA0749.2', 'MA1971.2', 'MA1649.2',
       'MA1650.2', 'MA0698.2', 'MA1579.2', 'MA0527.2', 'MA1581.2',
       'MA0750.3', 'MA0694.2', 'MA0695.2', 'MA0103.4', 'MA1651.2',
       'MA1583.2', 'MA0751.2', 'MA1584.2', 'MA1709.2', 'MA1585.2',
       'MA1973.2', 'MA1652.2', 'MA1589.2', 'MA1653.2', 'MA1654.2',
       'MA1725.2', 'MA1974.2', 'MA1975.2', 'MA1710.2', 'MA0528.3',
       'MA1592.2', 'MA1630.3', 'MA1154.2', 'MA1593.2', 'MA1976.2',
       'MA1977.2', 'MA1726.2', 'MA1655.2', 'MA1711.2', 'MA1978.2',
       'MA1125.2', 'MA0752.2', 'MA1979.2', 'MA1727.2', 'MA1656.2',
       'MA1712.2', 'MA1981.2', 'MA1728.2', 'MA1982.2', 'MA1983.2',
       'MA1713.2', 'MA1657.2', 'MA1984.2', 'MA1714.2', 'MA1729.2',
       'MA1599.2', 'MA1600.2', 'MA1986.2', 'MA1987.2', 'MA1730.2',
       'MA0753.3', 'MA1716.2', 'MA1731.2', 'MA1717.2', 'MA1719.2',
       'MA1720.2', 'MA1721.2', 'MA1602.2', 'MA1722.2'], dtype=object)

## end

In [2]:
adata = ad.read_h5ad("/workspaces/swarm/backend/uploads/job_1765267595498_f19ae350-7f14-4fdf-88d7-77a40d81c2c4/plasmidpoop/adata_tg_scores_w_chromvar.h5ad")

In [4]:
adata.uns["chromvar_moranI"]

,I,pval_norm,var_norm,pval_z_sim,pval_sim,var_sim,pval_norm_fdr_bh,pval_z_sim_fdr_bh,pval_sim_fdr_bh
MA0103.4,0.427083,0.000000,0.00022,0.000000,0.000999,0.000325,0.000000,0.000000,0.001651
MA0820.2,0.427083,0.000000,0.00022,0.000000,0.000999,0.000325,0.000000,0.000000,0.001651
MA1631.2,0.420992,0.000000,0.00022,0.000000,0.000999,0.000329,0.000000,0.000000,0.001651
MA1643.2,0.400297,0.000000,0.00022,0.000000,0.000999,0.000317,0.000000,0.000000,0.001651
MA1558.2,0.394429,0.000000,0.00022,0.000000,0.000999,0.000308,0.000000,0.000000,0.001651
...,...,...,...,...,...,...,...,...,...
MA2003.2,-0.013612,0.191791,0.00022,0.092102,0.083916,0.000104,0.223860,0.109638,0.100225
MA0838.1,-0.014704,0.172333,0.00022,0.085438,0.076923,0.000117,0.202794,0.102213,0.092333
MA1537.2,-0.017279,0.131654,0.00022,0.045340,0.042957,0.000106,0.159091,0.056177,0.053622
MA2094.1,-0.018968,0.108885,0.00022,0.050774,0.047952,0.000120,0.132467,0.062191,0.059342
MA0673.2,-0.021370,0.081582,0.00022,0.016077,0.011988,0.000103,0.102369,0.021362,0.016232

In [2]:
path_map = "/workspaces/swarm/backend/uploads/job_1764846398907_305db84d-db7e-4739-9cbf-d409adb3607b/plasmidpoop/adata_map.h5ad"

adata = ad.read_h5ad(path_map)

In [3]:
adata.X.sum(axis=1)

array([0.9999999 , 0.99999994, 1.        , ..., 1.        , 0.99999994,
       1.        ], dtype=float32)

In [4]:
adata.X.shape

(5220, 1448)

In [3]:
## 
path_tg = "/workspaces/swarm/backend/uploads/job_1764852912905_bad92a14-c8f8-4967-9057-400f4df997fa/dumpase1/adata_tg_scores.h5ad"

# read h5ad file
adata_tg = ad.read_h5ad(path_tg)

In [7]:
adata_tg.obsm["chromvar_spot_scores"]

array([[ 0.0516671 , -0.07554634, -0.15580814, ..., -0.1186061 ,
        -0.12716125,  0.05326991],
       [-0.07753974,  0.03307342,  0.02397189, ...,  0.04273946,
        -0.00117686, -0.02415787],
       [-0.13325831, -0.12116171, -0.08750205, ..., -0.09895314,
        -0.16519895,  0.00463829],
       ...,
       [-0.3863658 , -0.35589522, -0.02899457, ..., -0.50825256,
        -0.0554913 , -0.35734987],
       [-0.01965947, -0.01777472, -0.11490043, ..., -0.06122348,
         0.09398171,  0.01081097],
       [-0.03957746, -0.08878732, -0.17494355, ..., -0.10941954,
        -0.19588946,  0.0841109 ]], dtype=float32)

In [11]:
adata_tg.uns["chromvar_motifs"]

array(['MA0071.1', 'MA0074.1', 'MA0101.1', 'MA0107.1', 'MA0115.1',
       'MA0119.1', 'MA0130.1', 'MA0149.1', 'MA0155.1', 'MA0159.1',
       'MA0163.1', 'MA0468.1', 'MA0258.2', 'MA0595.1', 'MA0596.1',
       'MA0599.1', 'MA0613.1', 'MA0636.1', 'MA0641.1', 'MA0042.2',
       'MA0033.2', 'MA0153.2', 'MA0486.2', 'MA0653.1', 'MA0655.1',
       'MA0660.1', 'MA0663.1', 'MA0665.1', 'MA0667.1', 'MA0669.1',
       'MA0678.1', 'MA0068.2', 'MA0083.3', 'MA0009.2', 'MA0689.1',
       'MA0691.1', 'MA0696.1', 'MA0713.1', 'MA0715.1', 'MA0724.1',
       'MA0729.1', 'MA0730.1', 'MA0731.1', 'MA0472.2', 'MA0736.1',
       'MA0737.1', 'MA0741.1', 'MA0088.2', 'MA0758.1', 'MA0770.1',
       'MA0771.1', 'MA0773.1', 'MA0774.1', 'MA0776.1', 'MA0777.1',
       'MA0105.4', 'MA0780.1', 'MA0783.1', 'MA0787.1', 'MA0788.1',
       'MA0789.1', 'MA0792.1', 'MA0794.1', 'MA0795.1', 'MA0796.1',
       'MA0797.1', 'MA0511.2', 'MA0801.1', 'MA0803.1', 'MA0805.1',
       'MA0806.1', 'MA0807.1', 'MA0808.1', 'MA0813.1', 'MA0815.1',
       'MA0822.1', 'MA0823.1', 'MA0826.1', 'MA0827.1', 'MA0838.1',
       'MA0845.1', 'MA0032.2', 'MA0848.1', 'MA0849.1', 'MA0850.1',
       'MA0855.1', 'MA0856.1', 'MA0525.2', 'MA0106.3', 'MA0862.1',
       'MA0863.1', 'MA0024.3', 'MA0866.1', 'MA0872.1', 'MA1124.1',
       'MA1155.1', 'MA1127.1', 'MA1129.1', 'MA1136.1', 'MA1420.1',
       'MA1421.1', 'MA1468.1', 'MA1485.1', 'MA1489.1', 'MA1493.1',
       'MA1509.1', 'MA1538.1', 'MA1539.1', 'MA1555.1', 'MA1556.1',
       'MA1557.1', 'MA1570.1', 'MA1571.1', 'MA1572.1', 'MA1580.1',
       'MA1587.1', 'MA1588.1', 'MA1594.1', 'MA1596.1', 'MA1597.1',
       'MA0158.2', 'MA0912.2', 'MA0623.2', 'MA2093.1', 'MA2094.1',
       'MA2096.1', 'MA1715.1', 'MA2097.1', 'MA2098.1', 'MA2099.1',
       'MA1718.1', 'MA2100.1', 'MA2101.1', 'MA2102.1', 'MA1931.1',
       'MA1957.1', 'MA1962.1', 'MA1972.1', 'MA1980.1', 'MA1985.1',
       'MA2117.1', 'MA2118.1', 'MA2119.1', 'MA2120.1', 'MA2121.1',
       'MA0079.5', 'MA0509.3', 'MA0516.3', 'MA0607.2', 'MA0685.2',
       'MA0740.2', 'MA0742.2', 'MA0798.3', 'MA0818.2', 'MA0821.2',
       'MA0831.3', 'MA0878.3', 'MA0884.2', 'MA1511.2', 'MA1532.2',
       'MA1547.2', 'MA1563.2', 'MA1601.2', 'MA1633.2', 'MA2324.1',
       'MA2325.1', 'MA2326.1', 'MA2327.1', 'MA2328.1', 'MA2329.1',
       'MA2330.1', 'MA2331.1', 'MA2332.1', 'MA2333.1', 'MA2334.1',
       'MA2335.1', 'MA2336.1', 'MA2341.1', 'MA0634.2', 'MA0690.3',
       'MA1463.2', 'MA0259.2', 'MA1464.2', 'MA1100.3', 'MA1631.2',
       'MA1632.2', 'MA0605.3', 'MA0833.3', 'MA1466.2', 'MA0834.2',
       'MA0496.4', 'MA1101.3', 'MA1470.2', 'MA0877.4', 'MA0635.2',
       'MA0875.2', 'MA1471.2', 'MA1634.2', 'MA0462.3', 'MA0488.2',
       'MA0835.3', 'MA0463.3', 'MA1635.2', 'MA0817.2', 'MA0464.3',
       'MA1928.2', 'MA0876.2', 'MA0465.3', 'MA1473.2', 'MA0102.5',
       'MA0466.4', 'MA0836.3', 'MA0837.3', 'MA1636.2', 'MA0819.3',
       'MA0018.5', 'MA0638.2', 'MA0839.2', 'MA1474.2', 'MA1475.2',
       'MA0609.3', 'MA0139.2', 'MA1929.2', 'MA1930.2', 'MA1102.3',
       'MA0754.3', 'MA0901.3', 'MA0755.2', 'MA0639.2', 'MA0879.3',
       'MA0882.2', 'MA0610.2', 'MA1707.2', 'MA1478.2', 'MA1479.2',
       'MA1480.2', 'MA1481.2', 'MA0864.3', 'MA0469.4', 'MA0756.3',
       'MA0470.3', 'MA0471.3', 'MA0865.3', 'MA0154.5', 'MA1637.2',
       'MA0162.5', 'MA0732.2', 'MA0733.2', 'MA0598.4', 'MA0473.4',
       'MA1483.3', 'MA0640.3', 'MA0028.3', 'MA0800.2', 'MA1708.2',
       'MA1495.2', 'MA1932.2', 'MA0779.2', 'MA0014.4', 'MA0781.2',
       'MA0686.2', 'MA1933.2', 'MA0828.3', 'MA0843.2', 'MA0759.3',
       'MA0076.3', 'MA0612.3', 'MA0886.2', 'MA0027.3', 'MA0642.3',
       'MA0760.2', 'MA1934.2', 'MA0820.2', 'MA1935.2', 'MA1936.2',
       'MA1937.2', 'MA0058.4', 'MA1938.2', 'MA0048.3', 'MA1939.2',
       'MA0112.4', 'MA0592.4', 'MA0141.4', 'MA0644.3', 'MA0098.4',
       'MA1484.2', 'MA0761.3', 'MA0762.2', 'MA1940.2', 'MA1941.2',
       'MA1942.2', 'MA1943.2', 'MA0763.2', 'MA0764.4', 'MA0765.4',
       'MA1944.2', 'MA1945.2', 'MA1946.2', 'MA1947.2', 'MA1948.2',
       'MA0900.3', 'MA0645.2', 'MA0887.2', 'MA0888.2', 'MA0156.4',
       'MA0475.3', 'MA1949.2', 'MA1950.2', 'MA0476.2', 'MA1951.2',
       'MA0099.4', 'MA1126.2', 'MA1134.2', 'MA1140.3', 'MA0490.3',
       'MA1141.2', 'MA0492.2', 'MA0491.3', 'MA1135.2', 'MA0477.3',
       'MA1128.2', 'MA1137.2', 'MA1142.2', 'MA1143.2', 'MA0478.2',
       'MA1130.2', 'MA1131.2', 'MA1138.2', 'MA1139.2', 'MA1144.2',
       'MA1145.2', 'MA0148.5', 'MA0047.4', 'MA1683.2', 'MA0846.2',
       'MA0031.2', 'MA0847.4', 'MA0041.3', 'MA1487.3', 'MA0030.2',
       'MA0479.2', 'MA1952.2', 'MA0682.3', 'MA0852.3', 'MA1103.3',
       'MA1953.2', 'MA1954.2', 'MA1955.2', 'MA1956.2', 'MA0481.4',
       'MA0593.2', 'MA0062.4', 'MA0035.5', 'MA0140.3', 'MA0036.4',
       'MA0482.3', 'MA0766.3', 'MA1104.3', 'MA0889.2', 'MA0890.2',
       'MA0646.2', 'MA0143.5', 'MA0767.2', 'MA0038.3', 'MA1491.3',
       'MA0735.2', 'MA0647.2', 'MA1105.3', 'MA0648.2', 'MA0891.2',
       'MA0892.2', 'MA0893.3', 'MA0522.4', 'MA1638.2', 'MA1099.3',
       'MA0616.3', 'MA0894.2', 'MA0649.2', 'MA0738.2', 'MA1106.2',
       'MA0131.3', 'MA0043.4', 'MA0895.2', 'MA0046.3', 'MA1494.2',
       'MA0114.5', 'MA0484.3', 'MA0899.2', 'MA1496.2', 'MA1497.2',
       'MA1498.3', 'MA0594.3', 'MA0902.3', 'MA1566.3', 'MA0903.2',
       'MA1499.2', 'MA0904.3', 'MA1500.2', 'MA1501.2', 'MA1502.2',
       'MA1503.2', 'MA0905.2', 'MA0651.3', 'MA0906.2', 'MA0907.2',
       'MA1504.2', 'MA1505.2', 'MA0485.3', 'MA1506.2', 'MA0908.2',
       'MA0873.2', 'MA1958.2', 'MA1507.2', 'MA0910.3', 'MA0913.3',
       'MA1508.2', 'MA0051.2', 'MA1418.2', 'MA1419.2', 'MA0772.2',
       'MA0652.2', 'MA0914.2', 'MA0654.2', 'MA0656.2', 'MA1132.2',
       'MA1133.2', 'MA0493.3', 'MA1512.2', 'MA0657.2', 'MA1513.2',
       'MA1514.2', 'MA1515.2', 'MA1516.2', 'MA0039.5', 'MA1517.2',
       'MA1959.2', 'MA1107.3', 'MA0618.2', 'MA0699.2', 'MA0700.3',
       'MA1519.2', 'MA0658.2', 'MA0701.3', 'MA0702.3', 'MA0703.3',
       'MA1520.2', 'MA0501.2', 'MA0841.2', 'MA1521.2', 'MA0495.4',
       'MA0089.3', 'MA0059.2', 'MA0147.4', 'MA1522.2', 'MA0052.5',
       'MA0497.2', 'MA0498.3', 'MA1639.2', 'MA1640.2', 'MA0775.2',
       'MA0661.2', 'MA0706.2', 'MA1960.2', 'MA0620.4', 'MA0662.2',
       'MA0664.2', 'MA0825.2', 'MA0707.3', 'MA1523.2', 'MA0666.3',
       'MA0708.3', 'MA1108.3', 'MA0100.4', 'MA0104.5', 'MA1641.2',
       'MA0499.3', 'MA0500.3', 'MA0056.3', 'MA1109.2', 'MA1642.2',
       'MA0625.3', 'MA1525.3', 'MA0670.2', 'MA1643.2', 'MA0161.3',
       'MA1527.2', 'MA0025.3', 'MA0671.2', 'MA1528.2', 'MA0778.2',
       'MA0060.4', 'MA0502.3', 'MA1644.2', 'MA1529.2', 'MA1645.2',
       'MA0672.2', 'MA2003.2', 'MA0063.3', 'MA0673.2', 'MA0674.2',
       'MA0675.2', 'MA1530.2', 'MA0710.2', 'MA1531.2', 'MA1146.2',
       'MA1533.2', 'MA1534.2', 'MA1535.2', 'MA0504.2', 'MA1536.2',
       'MA0017.3', 'MA1537.2', 'MA1111.2', 'MA0113.4', 'MA0727.2',
       'MA1112.3', 'MA0160.3', 'MA1147.2', 'MA1541.2', 'MA0842.3',
       'MA0679.3', 'MA0757.2', 'MA1542.2', 'MA1646.2', 'MA0711.2',
       'MA0712.3', 'MA1544.2', 'MA1545.2', 'MA1961.2', 'MA0067.3',
       'MA1546.2', 'MA0070.2', 'MA1113.3', 'MA1114.2', 'MA0132.3',
       'MA0681.3', 'MA0714.2', 'MA0782.3', 'MA1548.2', 'MA0784.3',
       'MA0785.2', 'MA0507.3', 'MA0627.3', 'MA0786.2', 'MA0790.2',
       'MA0683.2', 'MA0791.2', 'MA1115.2', 'MA0628.2', 'MA1549.2',
       'MA0793.2', 'MA1148.2', 'MA1550.2', 'MA0066.2', 'MA0508.4',
       'MA1723.2', 'MA0716.2', 'MA0075.4', 'MA1149.2', 'MA1552.2',
       'MA1553.2', 'MA0718.2', 'MA0717.2', 'MA1116.2', 'MA1117.2',
       'MA0138.3', 'MA0600.3', 'MA0799.3', 'MA0510.3', 'MA1554.2',
       'MA0719.2', 'MA0072.2', 'MA1150.2', 'MA1151.2', 'MA0073.2',
       'MA0684.3', 'MA1963.2', 'MA0743.3', 'MA0744.3', 'MA0630.2',
       'MA1118.2', 'MA1119.2', 'MA1964.2', 'MA1558.2', 'MA0745.3',
       'MA1559.2', 'MA1560.2', 'MA0442.3', 'MA1561.2', 'MA1120.2',
       'MA1562.2', 'MA1152.2', 'MA0867.3', 'MA0868.3', 'MA0077.2',
       'MA0746.3', 'MA1965.2', 'MA0747.2', 'MA1564.2', 'MA0081.3',
       'MA0687.2', 'MA0829.3', 'MA0084.2', 'MA0137.4', 'MA0517.2',
       'MA0144.3', 'MA0091.2', 'MA0802.2', 'MA1565.2', 'MA0804.2',
       'MA0688.2', 'MA1648.2', 'MA1568.2', 'MA0830.3', 'MA0769.3',
       'MA0523.2', 'MA0632.3', 'MA0090.4', 'MA1121.2', 'MA0809.3',
       'MA0810.2', 'MA0003.5', 'MA0811.2', 'MA0812.2', 'MA0524.3',
       'MA0814.3', 'MA1569.2', 'MA1966.2', 'MA1967.2', 'MA1968.2',
       'MA1122.2', 'MA0692.2', 'MA0871.3', 'MA0597.3', 'MA1969.2',
       'MA1574.2', 'MA1575.2', 'MA1576.2', 'MA1577.2', 'MA0861.2',
       'MA1970.2', 'MA1123.3', 'MA0721.2', 'MA0093.4', 'MA0526.5',
       'MA0722.2', 'MA0723.3', 'MA1578.2', 'MA0725.2', 'MA0726.2',
       'MA0844.2', 'MA0748.3', 'MA0749.2', 'MA1971.2', 'MA1649.2',
       'MA1650.2', 'MA0698.2', 'MA1579.2', 'MA0527.2', 'MA1581.2',
       'MA0750.3', 'MA0694.2', 'MA0695.2', 'MA0103.4', 'MA1651.2',
       'MA1583.2', 'MA0751.2', 'MA1584.2', 'MA1709.2', 'MA1585.2',
       'MA1973.2', 'MA1652.2', 'MA1589.2', 'MA1653.2', 'MA1654.2',
       'MA1725.2', 'MA1974.2', 'MA1975.2', 'MA1710.2', 'MA0528.3',
       'MA1592.2', 'MA1630.3', 'MA1154.2', 'MA1593.2', 'MA1976.2',
       'MA1977.2', 'MA1726.2', 'MA1655.2', 'MA1711.2', 'MA1978.2',
       'MA1125.2', 'MA0752.2', 'MA1979.2', 'MA1727.2', 'MA1656.2',
       'MA1712.2', 'MA1981.2', 'MA1728.2', 'MA1982.2', 'MA1983.2',
       'MA1713.2', 'MA1657.2', 'MA1984.2', 'MA1714.2', 'MA1729.2',
       'MA1599.2', 'MA1600.2', 'MA1986.2', 'MA1987.2', 'MA1730.2',
       'MA0753.3', 'MA1716.2', 'MA1731.2', 'MA1717.2', 'MA1719.2',
       'MA1720.2', 'MA1721.2', 'MA1602.2', 'MA1722.2'], dtype=object)

In [17]:
import scanpy as sc
import pandas as pd
def load_adata(path: str) -> sc.AnnData:
    spatial_data = sc.read_h5ad(path)

    # Reconstruct liana columns for placeholder fields in the geojson
    reconstruct_obsm_cols = {
        "ligand_receptor_cosine_similarity": "ligand_receptor",
        "cell_comp_tf_activity_cosine_similarity": "cell_comp_tf_activity",
    }
    for obsm_key, col_names_key in reconstruct_obsm_cols.items():
        if (
            obsm_key in spatial_data.obsm
            and "liana_columns" in spatial_data.uns
        ):
            spatial_data.obsm[obsm_key] = pd.DataFrame(
                spatial_data.obsm[obsm_key],
                columns=spatial_data.uns["liana_columns"][col_names_key],
                index=spatial_data.obs_names,
            )

    # ⬇⬇⬇ NEW: make chromVAR motif activity usable by name
    if (
        "chromvar_spot_scores" in spatial_data.obsm
        and "chromvar_motifs" in spatial_data.uns
    ):
        motif_names = list(spatial_data.uns["chromvar_motifs"])
        spatial_data.obsm["chromvar_activity"] = pd.DataFrame(
            spatial_data.obsm["chromvar_spot_scores"],
            index=spatial_data.obs_names,
            columns=motif_names,
        )

    return spatial_data

In [18]:
adata_tg = load_adata(path_tg)

In [20]:
adata_tg.obsm["chromvar_activity"]

,MA0071.1,MA0074.1,MA0101.1,MA0107.1,MA0115.1,MA0119.1,MA0130.1,MA0149.1,MA0155.1,MA0159.1,...,MA1730.2,MA0753.3,MA1716.2,MA1731.2,MA1717.2,MA1719.2,MA1720.2,MA1721.2,MA1602.2,MA1722.2
AAACACCAATAACTGC-1,0.051667,-0.075546,-0.155808,-0.054295,-0.032455,-0.199132,-0.118896,-0.223373,-0.103841,-0.051261,...,-0.044454,-0.067191,0.026455,-0.304280,0.046654,-0.154886,0.026338,-0.118606,-0.127161,0.053270
AAACAGCTTTCAGAAG-1,-0.077540,0.033073,0.023972,0.038106,-0.079636,-0.149501,-0.051291,-0.132546,-0.048376,0.081989,...,-0.139281,-0.042961,0.053077,-0.160133,-0.031399,-0.167937,-0.012776,0.042739,-0.001177,-0.024158
AAACAGGGTCTATATT-1,-0.133258,-0.121162,-0.087502,-0.098506,-0.027875,-0.245846,-0.131217,-0.251323,-0.155614,-0.125177,...,-0.129253,-0.273297,-0.022866,-0.131374,-0.153349,-0.273374,-0.203774,-0.098953,-0.165199,0.004638
AAACCGGGTAGGTACC-1,-0.028207,-0.147308,-0.218436,-0.230513,0.007473,-0.253516,-0.129877,-0.236601,-0.211165,-0.213166,...,-0.218132,-0.134716,-0.068701,-0.222065,0.145564,-0.163332,-0.237173,-0.192399,-0.042302,-0.315173
AAACCTCATGAAGTTG-1,-0.245287,-0.016640,-0.268666,-0.211775,-0.019556,-0.482550,-0.110716,-0.311911,-0.087240,-0.074865,...,-0.519845,-0.166693,-0.050747,-0.242280,0.214319,-0.106049,0.026559,-0.107308,-0.054735,-0.194147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTGTGTTTCCCGAAAG-1,-0.005880,-0.155999,-0.095763,-0.018906,-0.095127,-0.119681,-0.108443,-0.122676,0.037335,-0.061566,...,-0.133378,-0.044189,0.071908,-0.165849,-0.106167,-0.175380,-0.027392,0.057516,-0.122943,-0.114337
TTGTTAGCAAATTCGA-1,-0.118819,-0.074736,-0.201167,-0.154919,-0.071799,-0.289628,-0.163801,-0.304688,-0.176468,-0.090034,...,-0.305638,-0.084718,0.050039,-0.156872,-0.049775,-0.341949,-0.293200,-0.194449,-0.063146,0.004039
TTGTTCAGTGTGCTAC-1,-0.386366,-0.355895,-0.028995,-0.099543,-0.048556,-0.005009,-0.376462,-0.175748,-0.052352,0.048001,...,-0.413212,0.042848,-0.203986,-0.230014,-0.157619,-0.215867,-0.400689,-0.508253,-0.055491,-0.357350
TTGTTTCACATCCAGG-1,-0.019659,-0.017775,-0.114900,-0.171826,-0.012276,-0.169094,-0.043269,-0.074611,-0.101072,0.013019,...,-0.300958,0.046640,-0.008077,-0.215949,-0.100982,-0.141490,-0.129530,-0.061223,0.093982,0.010811
TTGTTTCCATACAACT-1,-0.039577,-0.088787,-0.174944,-0.170198,-0.010400,-0.295923,-0.040029,-0.281220,-0.181013,-0.050282,...,-0.227599,-0.147719,-0.023111,-0.164108,-0.147861,-0.289505,-0.249357,-0.109420,-0.195889,0.084111

In [6]:
# read chromvar scores
import pandas as pd
path = "/workspaces/swarm/backend/uploads/job_1764846398907_305db84d-db7e-4739-9cbf-d409adb3607b/plasmidpoop/multiome/chromvar_scores.csv"
chromvar = pd.read_csv(path)

In [7]:
import numpy as np
np.array(chromvar).shape

(5220, 721)

In [ ]:
import numpy as np
from scipy import sparse
# adata is the AnnData object containing the mapping
M = adata.X
S = np.array(chromvar)[:,1:]

M = np.asarray(M, dtype=np.float32) 
S = np.asarray(S, dtype=np.float32)

spot_chromvar = M.T @ S

In [19]:
chromvar.columns[1:]

Index(['MA0069.1', 'MA0071.1', 'MA0074.1', 'MA0101.1', 'MA0107.1', 'MA0115.1',
       'MA0119.1', 'MA0130.1', 'MA0149.1', 'MA0155.1',
       ...
       'MA1730.2', 'MA0753.3', 'MA1716.2', 'MA1731.2', 'MA1717.2', 'MA1719.2',
       'MA1720.2', 'MA1721.2', 'MA1602.2', 'MA1722.2'],
      dtype='object', length=720)

In [12]:
spot_chromvar.shape

(1448, 720)

In [15]:
spot_chromvar

array([[-0.2114042 ,  0.1404319 , -0.02753818, ..., -0.17679638,
        -0.00593853,  0.07364926],
       [-0.02475275, -0.06552906, -0.00047354, ...,  0.06818644,
         0.0139944 ,  0.02456195],
       [-0.24588808, -0.05241064, -0.13212763, ..., -0.13721813,
        -0.1694049 , -0.00923056],
       ...,
       [ 0.2619109 , -0.22806892, -0.24894798, ..., -0.46382314,
        -0.04261723, -0.26055357],
       [ 0.03505917,  0.00401011,  0.01721881, ..., -0.06699559,
         0.09286542,  0.03331326],
       [-0.12569836, -0.11718678, -0.18501832, ..., -0.12552905,
        -0.18131301,  0.06859598]], dtype=float32)

In [14]:
adata_tg.obs

,in_tissue,array_row,array_col,suspension_type,assay_ontology_term_id,Sample_ID,organism_ontology_term_id,sex_ontology_term_id,development_stage_ontology_term_id,self_reported_ethnicity_ontology_term_id,...,disease,organism,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid,leiden,uniform_density,rna_count_based_density
AAACACCAATAACTGC-1,1,59,19,na,EFO:0022857,CL-like1,NCBITaxon:9606,PATO:0000383,HsapDv:0000258,unknown,...,triple-negative breast carcinoma,Homo sapiens,female,breast,unknown,adult stage,zuU(#yRj2=,0,0.000691,0.000636
AAACAGCTTTCAGAAG-1,1,43,9,na,EFO:0022857,CL-like1,NCBITaxon:9606,PATO:0000383,HsapDv:0000258,unknown,...,triple-negative breast carcinoma,Homo sapiens,female,breast,unknown,adult stage,U@Q8P(aq*%,2,0.000691,0.000336
AAACAGGGTCTATATT-1,1,47,13,na,EFO:0022857,CL-like1,NCBITaxon:9606,PATO:0000383,HsapDv:0000258,unknown,...,triple-negative breast carcinoma,Homo sapiens,female,breast,unknown,adult stage,O3sm{X3xkp,2,0.000691,0.000434
AAACCGGGTAGGTACC-1,1,42,28,na,EFO:0022857,CL-like1,NCBITaxon:9606,PATO:0000383,HsapDv:0000258,unknown,...,triple-negative breast carcinoma,Homo sapiens,female,breast,unknown,adult stage,59a1x9<Bwm,0,0.000691,0.000693
AAACCTCATGAAGTTG-1,1,37,19,na,EFO:0022857,CL-like1,NCBITaxon:9606,PATO:0000383,HsapDv:0000258,unknown,...,triple-negative breast carcinoma,Homo sapiens,female,breast,unknown,adult stage,ZUJOvK3P_p,0,0.000691,0.000638
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTGTGTTTCCCGAAAG-1,1,51,59,na,EFO:0022857,CL-like1,NCBITaxon:9606,PATO:0000383,HsapDv:0000258,unknown,...,triple-negative breast carcinoma,Homo sapiens,female,breast,unknown,adult stage,w<d=)hc%J=,2,0.000691,0.000423
TTGTTAGCAAATTCGA-1,1,22,42,na,EFO:0022857,CL-like1,NCBITaxon:9606,PATO:0000383,HsapDv:0000258,unknown,...,triple-negative breast carcinoma,Homo sapiens,female,breast,unknown,adult stage,P(DZ46JPTe,1,0.000691,0.000889
TTGTTCAGTGTGCTAC-1,1,24,64,na,EFO:0022857,CL-like1,NCBITaxon:9606,PATO:0000383,HsapDv:0000258,unknown,...,triple-negative breast carcinoma,Homo sapiens,female,breast,unknown,adult stage,!;OpdIV!{r,5,0.000691,0.000796
TTGTTTCACATCCAGG-1,1,58,42,na,EFO:0022857,CL-like1,NCBITaxon:9606,PATO:0000383,HsapDv:0000258,unknown,...,triple-negative breast carcinoma,Homo sapiens,female,breast,unknown,adult stage,!-K_Z3vDq*,2,0.000691,0.000433
TTGTTTCCATACAACT-1,1,45,27,na,EFO:0022857,CL-like1,NCBITaxon:9606,PATO:0000383,HsapDv:0000258,unknown,...,triple-negative breast carcinoma,Homo sapiens,female,breast,unknown,adult stage,ZuyRYj_t<2,0,0.000691,0.000708

In [ ]:
mapping = adata.X.copy()


spot_chromvar = mapping.T @ chromvar_scores
spot_chromvar.shape

## old

In [ ]:
adata.var

,vf_vst_counts_mean,vf_vst_counts_variance,vf_vst_counts_variance.expected,vf_vst_counts_variance.standardized,vf_vst_counts_variable,vf_vst_counts_rank,var.features,var.features.rank
FAM87B,0.002107,0.003636,0.002367,1.536203,1,1700,FAM87B,1700
HES5,0.001341,0.002872,0.001456,1.789769,1,1100,HES5,1100
GPR153,0.018199,0.108310,0.023883,1.658630,1,1377,GPR153,1377
UTS2,0.002299,0.003827,0.002601,1.471214,1,1929,UTS2,1929
AL034417.2,0.031801,0.166070,0.042958,3.288904,1,227,AL034417.2,227
...,...,...,...,...,...,...,...,...
GABRE,0.281609,1.277646,0.557782,2.290583,1,565,GABRE,565
AC116666.1,0.001724,0.002871,0.001905,1.507151,1,1807,AC116666.1,1807
BGN,0.004023,0.007457,0.004786,1.557845,1,1625,BGN,1625
AC245140.3,0.005747,0.046719,0.006987,1.521235,1,1764,AC245140.3,1764
F8,0.117816,0.346914,0.185934,1.865785,1,967,F8,967

In [ ]:
spatialh5ad = "/workspaces/swarm/backend/uploads/job_1764336482865_merit/adata.h5ad"
spatial = ad.read_h5ad(spatialh5ad)

In [ ]:
spatial.var.index.intersection(adata.var.index)

Index(['ABCA10', 'ABCA4', 'ABCA6', 'ABCA8', 'ABCA9', 'ABCB1', 'ABCB5',
       'ABCC11', 'ABCC9', 'ABCD2',
       ...
       'ZNF365', 'ZNF385B', 'ZNF385C', 'ZNF385D', 'ZNF576', 'ZNF653', 'ZNF672',
       'ZNF804A', 'ZNF843', 'ZP2'],
      dtype='object', length=1404)

In [ ]:
adata.obs["orig.ident"].unique()

array([0], dtype=int32)

In [ ]:
adata.obs
"RNA_peaks_clusters_res0.1"

,orig.ident,nCount_RNA,nFeature_RNA,nCount_ATAC,nFeature_ATAC,percent.mt,nucleosome_signal,nucleosome_percentile,TSS.enrichment,TSS.percentile,...,nCount_SCT,nFeature_SCT,RNA.weight,peaks.weight,RNA_peaks_clusters_res0.2,RNA_peaks_clusters_res0.1,RNA_peaks_clusters_res0.05,SCT.weight,SCT_peaks_clusters_res0.2,SCT_peaks_clusters_res0.1
AAACAGCCAAACTAAG-1,0,5984.0,3067,822.0,445,0.100267,0.969231,0.16,4.865723,0.87,...,1773.0,1264,0.317982,0.247865,1,1,1,0.752135,1,1
AAACAGCCAAAGCTAA-1,0,2622.0,1407,2315.0,1194,0.000000,0.866029,0.10,4.199134,0.64,...,2332.0,1405,0.425636,0.975121,3,3,3,0.024879,3,3
AAACAGCCACCTAATG-1,0,7845.0,3169,9264.0,4768,0.025494,1.607815,0.90,3.636191,0.30,...,2012.0,1263,0.678550,0.245549,4,4,5,0.754451,4,4
AAACATGCAAACATAG-1,0,525.0,461,975.0,527,0.000000,1.125000,0.31,4.317422,0.70,...,1209.0,488,0.395767,0.837649,0,0,0,0.162351,0,0
AAACATGCACAAGCCT-1,0,1422.0,999,15954.0,7333,0.281294,1.144059,0.33,4.218566,0.65,...,1610.0,999,0.558170,0.298276,0,0,0,0.701724,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTGTTCTATGACA-1,0,2010.0,1354,7906.0,4008,0.099502,0.795602,0.07,3.118420,0.10,...,2006.0,1351,0.397593,0.362255,1,1,1,0.637745,6,1
TTTGTGTTCTGTGAGT-1,0,2630.0,1464,17096.0,7766,0.038023,1.309403,0.60,4.184102,0.64,...,2367.0,1460,0.545662,0.469546,6,6,6,0.530454,7,6
TTTGTTGGTAACGGGA-1,0,757.0,584,12972.0,5630,0.792602,1.375000,0.70,4.742737,0.84,...,1510.0,594,0.306528,0.853402,5,5,4,0.146598,5,5
TTTGTTGGTGAAACAA-1,0,1793.0,1271,25179.0,10999,0.000000,1.366284,0.69,3.788949,0.39,...,1801.0,1271,0.247317,0.784392,1,1,1,0.215608,1,1
TTTGTTGGTGATGAAA-1,0,759.0,614,26316.0,12417,0.395257,1.908809,0.97,2.965351,0.07,...,1538.0,614,0.512278,0.602292,4,4,5,0.397708,4,4

In [ ]:
adata

## look at input for tangram

In [12]:
## 
path_rds = "/workspaces/swarm/backend/uploads/job_1764512807100_merit/healthy_breast_preprocessed_RNA_peaks_only.h5ad"

# read h5ad file
adata_in = ad.read_h5ad(path_rds)

/opt/conda/lib/python3.11/site-packages/anndata/compat/__init__.py:371: FutureWarning: Moving element from .uns['neighbors']['distances'] to .obsp['distances'].

This is where adjacency matrices should go now.
  warn(

In [13]:
adata_in

AnnData object with n_obs × n_vars = 5220 × 2000
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'nCount_ATAC', 'nFeature_ATAC', 'percent.mt', 'nucleosome_signal', 'nucleosome_percentile', 'TSS.enrichment', 'TSS.percentile', 'nCount_peaks', 'nFeature_peaks', 'nCount_SCT', 'nFeature_SCT', 'RNA.weight', 'peaks.weight', 'RNA_peaks_clusters_res0.2', 'RNA_peaks_clusters_res0.1', 'RNA_peaks_clusters_res0.05', 'SCT.weight', 'SCT_peaks_clusters_res0.2', 'SCT_peaks_clusters_res0.1'
    var: 'vf_vst_counts_mean', 'vf_vst_counts_variance', 'vf_vst_counts_variance.expected', 'vf_vst_counts_variance.standardized', 'vf_vst_counts_variable', 'vf_vst_counts_rank', 'var.features', 'var.features.rank'
    uns: 'neighbors'
    obsm: 'X_pca_rna', 'X_umap_RNA_peaks'
    varm: 'PCA_RNA'
    obsp: 'distances'

## look at tangram

In [18]:
## 
path_rds = "/workspaces/swarm/backend/uploads/job_1764512807100_merit/kackhaufen1/adata_tg_scores.h5ad"

# read h5ad file
adata = ad.read_h5ad(path_rds)

In [5]:
adata

AnnData object with n_obs × n_vars = 1448 × 2000
    obs: 'in_tissue', 'array_row', 'array_col', 'suspension_type', 'assay_ontology_term_id', 'Sample_ID', 'organism_ontology_term_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'pathologist_annotation', 'B-cells', 'CAFs', 'Cancer Epithelial', 'Endothelial', 'Myeloid', 'Normal Epithelial', 'PVL', 'T-cells', 'stereoscope_annotation', 'cell_type_ontology_term_id', 'is_primary_data', 'treatment', 'donor_id', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'leiden', 'uniform_density', 'rna_count_based_density'
    var: 'vf_vst_counts_mean', 'vf_vst_counts_variance', 'vf_vst_counts_variance.expected', 'vf_vst_counts_variance.standardized', 'vf_vst_counts_variable', 'vf_vst_counts_rank', 'var.features', 'var.features.rank', 'n_cells', 'is_training'
    uns: 'neighbors', 'overlap_genes', 'spatial', 'training_genes'
    obsm: 'spatial', 'tangram_ct_pred'

In [8]:
adata.obs.shape

(1448, 39)

In [10]:
adata.var.shape

(2000, 10)

### sc adata

In [2]:
## 
path_rds = "/workspaces/swarm/backend/uploads/job_1764512807100_merit/kackhaufen1/adata_st_scores.h5ad"

# read h5ad file
adata_st = ad.read_h5ad(path_rds)

In [3]:
adata_st

AnnData object with n_obs × n_vars = 1448 × 22616
    obs: 'in_tissue', 'array_row', 'array_col', 'suspension_type', 'assay_ontology_term_id', 'Sample_ID', 'organism_ontology_term_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'pathologist_annotation', 'B-cells', 'CAFs', 'Cancer Epithelial', 'Endothelial', 'Myeloid', 'Normal Epithelial', 'PVL', 'T-cells', 'stereoscope_annotation', 'cell_type_ontology_term_id', 'is_primary_data', 'treatment', 'donor_id', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'leiden', 'uniform_density', 'rna_count_based_density'
    var: 'feature_types', 'genome', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type', 'ensemble_id', 'n_cells', 'sparsity'
    uns: 'cell_comp_tf_activity_global_scores', 'citation', 'gearyC', 'genie_genesets', 'leiden', 'leiden_centrality_scores', 'leiden_co_occurrence', 'leiden_nhood_enrichment', 'liana_columns', 'ligand_receptor_global_scores', 'moranI', 'neighbors', 'overlap_genes', 'pca', 'schema_reference', 'schema_version', 'spatial', 'spatial_neighbors', 'sponge_genesets', 'title', 'training_genes', 'umap'
    obsm: 'X_pca', 'X_umap', 'aucell_scores_genie3', 'aucell_scores_sponge', 'cell_comp_tf_activity_category', 'cell_comp_tf_activity_cosine_similarity', 'celltype_scores', 'ligand_receptor_NMF_factors', 'ligand_receptor_category', 'ligand_receptor_cosine_similarity', 'ligand_receptor_p_value', 'pathway_activity_padj_mlm', 'pathway_activity_score_mlm', 'spatial', 'spongeffects_GSVA_scores_genie3', 'spongeffects_GSVA_scores_sponge', 'spongeffects_ssGSEA_scores_genie3', 'spongeffects_ssGSEA_scores_sponge', 'tf_activity_padj_ulm', 'tf_activity_score_ulm', 'viper_scores_genie3'
    varm: 'PCs'
    obsp: 'connectivities', 'distances', 'spatial_connectivities', 'spatial_distances'

In [11]:
# use the string accessor for Index objects
adata_st.var_names[adata_st.var_names.str.startswith("malat")]

Index(['malat1'], dtype='object')

In [5]:
adata_st.obsm["cell_comp_tf_activity_category"]

array([['low-low', 'high-high', 'high-low / low-high', ..., 'low-low',
        'high-low / low-high', 'low-low'],
       ['low-low', 'high-low / low-high', 'low-low', ..., 'high-high',
        'high-low / low-high', 'high-high'],
       ['high-low / low-high', 'high-low / low-high', 'low-low', ...,
        'high-low / low-high', 'high-low / low-high',
        'high-low / low-high'],
       ...,
       ['high-low / low-high', 'high-low / low-high', 'low-low', ...,
        'low-low', 'high-low / low-high', 'high-low / low-high'],
       ['high-low / low-high', 'low-low', 'high-low / low-high', ...,
        'high-low / low-high', 'high-high', 'high-high'],
       ['high-high', 'low-low', 'high-low / low-high', ...,
        'high-low / low-high', 'high-low / low-high', 'high-high']],
      dtype=object)

In [22]:
adata_in

AnnData object with n_obs × n_vars = 5220 × 2000
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'nCount_ATAC', 'nFeature_ATAC', 'percent.mt', 'nucleosome_signal', 'nucleosome_percentile', 'TSS.enrichment', 'TSS.percentile', 'nCount_peaks', 'nFeature_peaks', 'nCount_SCT', 'nFeature_SCT', 'RNA.weight', 'peaks.weight', 'RNA_peaks_clusters_res0.2', 'RNA_peaks_clusters_res0.1', 'RNA_peaks_clusters_res0.05', 'SCT.weight', 'SCT_peaks_clusters_res0.2', 'SCT_peaks_clusters_res0.1'
    var: 'vf_vst_counts_mean', 'vf_vst_counts_variance', 'vf_vst_counts_variance.expected', 'vf_vst_counts_variance.standardized', 'vf_vst_counts_variable', 'vf_vst_counts_rank', 'var.features', 'var.features.rank'
    uns: 'neighbors'
    obsm: 'X_pca_rna', 'X_umap_RNA_peaks'
    varm: 'PCA_RNA'
    obsp: 'distances'

## add chromvar scores correctly

In [2]:
#combine_files_multiome(filename, description, args, logfile):
import os
import scanpy as sc
import pandas as pd
filename = "adata_tg_scores.h5ad"
description = "tg"
indir = "/workspaces/swarm/backend/uploads/job_1764681017808_5209bb21-db67-439a-9820-a45d48ac8f01/kackhaufen1"
indir = "../backend/uploads/job_1764681017808_5209bb21-db67-439a-9820-a45d48ac8f01/kackhaufen1"


adata_path = os.path.join(indir, filename)
adata = sc.read_h5ad(adata_path)

print(f"AnnData object loaded")

AnnData object loaded

In [ ]:


scores_path = os.path.join(indir, "multiome")


for filename in os.listdir(scores_path):
    print(filename)
    if filename.endswith('.csv'):
        file_path = os.path.join(scores_path, filename)
        print(file_path)
        df = pd.read_csv(file_path, index_col=0)

        df_name = filename.replace(".csv", "")
        if df_name in adata.obsm.keys():
          print(f"The element with name {df_name} in obsm is overwritten.")
          adata.obsm[df_name] = df.T

AnnData object loaded
chromvar_scores.csv
/workspaces/swarm/backend/uploads/job_1764681017808_5209bb21-db67-439a-9820-a45d48ac8f01/kackhaufen1/multiome/chromvar_scores.csv

In [51]:
adata.obs.columns

Index(['in_tissue', 'array_row', 'array_col', 'suspension_type',
       'assay_ontology_term_id', 'Sample_ID', 'organism_ontology_term_id',
       'sex_ontology_term_id', 'development_stage_ontology_term_id',
       'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id',
       'tissue_type', 'tissue_ontology_term_id', 'pathologist_annotation',
       'B-cells', 'CAFs', 'Cancer Epithelial', 'Endothelial', 'Myeloid',
       'Normal Epithelial', 'PVL', 'T-cells', 'stereoscope_annotation',
       'cell_type_ontology_term_id', 'is_primary_data', 'treatment',
       'donor_id', 'cell_type', 'assay', 'disease', 'organism', 'sex',
       'tissue', 'self_reported_ethnicity', 'development_stage',
       'observation_joinid', 'leiden', 'uniform_density',
       'rna_count_based_density'],
      dtype='object')

In [53]:
adata.obsm["tangram_ct_pred"]

,0,1,2,3,4,5,6,7,8,9
AAACACCAATAACTGC-1,0.000222,0.000994,0.000727,0.001410,1.848478e-04,3.517333e-05,9.901220e-07,6.098959e-07,2.708361e-03,5.162564e-04
AAACAGCTTTCAGAAG-1,0.001045,0.000027,0.000076,0.000008,3.707386e-07,6.756055e-06,4.636307e-04,3.122374e-06,9.215981e-07,4.113053e-07
AAACAGGGTCTATATT-1,0.001229,0.000020,0.000005,0.000042,7.368504e-04,3.939113e-05,8.524284e-04,1.704032e-06,3.414039e-07,6.908706e-07
AAACCGGGTAGGTACC-1,0.000932,0.000964,0.000484,0.000493,4.026821e-04,6.929793e-04,1.218367e-07,7.735049e-04,5.160673e-07,2.045111e-06
AAACCTCATGAAGTTG-1,0.000932,0.000231,0.000398,0.000852,4.713694e-04,8.567648e-07,1.780041e-03,1.769616e-03,9.619900e-08,7.236334e-04
...,...,...,...,...,...,...,...,...,...,...
TTGTGTTTCCCGAAAG-1,0.000713,0.000006,0.000256,0.000238,1.205148e-05,2.066161e-03,5.550501e-07,6.508364e-04,9.639867e-04,1.450791e-06
TTGTTAGCAAATTCGA-1,0.000230,0.001209,0.001502,0.000803,9.527285e-04,3.373299e-06,5.256370e-05,6.272356e-04,2.688976e-03,4.907843e-03
TTGTTCAGTGTGCTAC-1,0.000010,0.001357,0.001524,0.000978,1.288542e-03,1.999705e-06,4.817136e-06,2.311712e-04,4.991179e-04,1.581082e-03
TTGTTTCACATCCAGG-1,0.001146,0.000016,0.000089,0.000665,8.760720e-07,5.933074e-04,4.578546e-07,1.047746e-06,1.163127e-07,1.148903e-06
TTGTTTCCATACAACT-1,0.000989,0.000679,0.000216,0.000371,7.692766e-04,1.966513e-03,4.108619e-04,4.836182e-04,8.830515e-04,2.031060e-06

In [ ]:
adata.obs.index.intersection(df.index)

Index([], dtype='object')

In [40]:
adata_spatial = ad.read_h5ad("/workspaces/swarm/backend/uploads/job_1764681017808_5209bb21-db67-439a-9820-a45d48ac8f01/adata.h5ad")

In [42]:
adata_spatial.obs.index.intersection(adata.obs.index)

Index(['AAACACCAATAACTGC-1', 'AAACAGCTTTCAGAAG-1', 'AAACAGGGTCTATATT-1',
       'AAACCGGGTAGGTACC-1', 'AAACCTCATGAAGTTG-1', 'AAACGAAGATGGAGTA-1',
       'AAACTGCTGGCTCCAA-1', 'AAACTTGCAAACGTAT-1', 'AAAGAATGACCTTAGA-1',
       'AAAGACTGGGCGCTTT-1',
       ...
       'TTGTCGTTCAGTTACC-1', 'TTGTGAACCTAATCCG-1', 'TTGTGCAGCCACGTCA-1',
       'TTGTGGTAGGAGGGAT-1', 'TTGTGTATGCCACCAA-1', 'TTGTGTTTCCCGAAAG-1',
       'TTGTTAGCAAATTCGA-1', 'TTGTTCAGTGTGCTAC-1', 'TTGTTTCACATCCAGG-1',
       'TTGTTTCCATACAACT-1'],
      dtype='object', length=1448)

In [23]:
adata.obsm[df_name] = df.T

ValueError: value.index does not match parent’s obs names:
Index are different

Index length are different
[left]:  720, Index(['MA0069.1', 'MA0071.1', 'MA0074.1', 'MA0101.1', 'MA0107.1', 'MA0115.1',
       'MA0119.1', 'MA0130.1', 'MA0149.1', 'MA0155.1',
       ...
       'MA1730.2', 'MA0753.3', 'MA1716.2', 'MA1731.2', 'MA1717.2', 'MA1719.2',
       'MA1720.2', 'MA1721.2', 'MA1602.2', 'MA1722.2'],
      dtype='object', length=720)
[right]: 1448, Index(['AAACACCAATAACTGC-1', 'AAACAGCTTTCAGAAG-1', 'AAACAGGGTCTATATT-1',
       'AAACCGGGTAGGTACC-1', 'AAACCTCATGAAGTTG-1', 'AAACGAAGATGGAGTA-1',
       'AAACTGCTGGCTCCAA-1', 'AAACTTGCAAACGTAT-1', 'AAAGAATGACCTTAGA-1',
       'AAAGACTGGGCGCTTT-1',
       ...
       'TTGTCGTTCAGTTACC-1', 'TTGTGAACCTAATCCG-1', 'TTGTGCAGCCACGTCA-1',
       'TTGTGGTAGGAGGGAT-1', 'TTGTGTATGCCACCAA-1', 'TTGTGTTTCCCGAAAG-1',
       'TTGTTAGCAAATTCGA-1', 'TTGTTCAGTGTGCTAC-1', 'TTGTTTCACATCCAGG-1',
       'TTGTTTCCATACAACT-1'],
      dtype='object', length=1448)

In [19]:
df.T

,AAACAGCCAAACTAAG-1,AAACAGCCAAAGCTAA-1,AAACAGCCACCTAATG-1,AAACATGCAAACATAG-1,AAACATGCACAAGCCT-1,AAACATGCACATAACT-1,AAACATGCACTAAATC-1,AAACATGCACTAAGAA-1,AAACATGCATAAACCT-1,AAACATGCATGTTGGC-1,...,TTTGTGGCACGTAAGG-1,TTTGTGGCATTGCGAC-1,TTTGTGTTCACATTGA-1,TTTGTGTTCCGCATGA-1,TTTGTGTTCGCCTGTT-1,TTTGTGTTCTATGACA-1,TTTGTGTTCTGTGAGT-1,TTTGTTGGTAACGGGA-1,TTTGTTGGTGAAACAA-1,TTTGTTGGTGATGAAA-1
MA0069.1,-0.698856,0.624814,-0.090265,-0.963445,0.302987,0.060803,0.680788,1.165812,-0.224385,-1.268993,...,-0.413893,-0.087337,-0.963660,-1.950400,-0.678516,-1.428645,1.957089,-1.165756,-0.241055,0.467383
MA0071.1,0.367152,0.785685,1.341399,-0.762809,-0.017648,0.387258,-0.479155,-0.076097,1.986480,-1.262342,...,0.010441,1.201203,-0.374929,-0.165618,-0.017311,-0.732818,1.774238,-0.347399,-0.271760,1.815948
MA0074.1,0.166133,-0.107041,0.455739,1.539214,0.631066,-0.124823,0.170361,2.975541,-0.619880,-1.996163,...,-0.084339,-1.038583,-1.107561,2.267442,0.286589,0.866190,1.079642,-1.165363,-1.071863,1.678581
MA0101.1,-0.103664,-0.030125,0.721069,-0.277056,-0.060820,4.943142,0.511421,0.243456,2.371131,-1.721802,...,1.753167,-0.061604,-1.290053,-0.709657,1.661663,0.131252,-0.403697,-2.221723,-0.159546,0.217706
MA0107.1,-0.415249,0.426775,0.122904,-0.588660,0.121404,3.090405,-0.255933,1.278827,2.952207,-0.399625,...,1.301208,-0.743476,-1.015180,-0.399361,0.494250,0.488340,1.566094,-5.166620,-0.741904,1.394968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MA1719.2,-0.443986,0.194546,0.428023,-1.133348,0.506812,0.999262,0.421329,-0.204272,1.914159,0.995788,...,-0.004958,-0.486990,-0.014760,-0.309062,0.501074,-0.333683,-0.990521,-3.459053,-1.154494,1.304448
MA1720.2,-2.325393,-0.198787,1.647218,1.138604,0.951303,0.636974,-1.232397,-0.370731,-0.719978,0.489057,...,-0.712967,-0.388855,0.090220,0.641436,0.003760,0.749467,1.135564,-1.285386,0.402514,3.078852
MA1721.2,-0.224141,0.366539,0.790551,0.707173,-0.180505,0.789415,-0.592646,-0.012577,-0.378848,-1.748631,...,-0.720893,-0.570465,-1.002387,0.701637,0.481233,-0.472877,0.325450,-2.040068,-1.624988,2.143196
MA1602.2,0.312302,0.982444,-0.218898,-0.207033,-0.743783,-0.224196,-0.040292,-1.097630,-0.393257,-0.304101,...,-0.290239,-0.874474,0.685725,1.255596,-0.896752,-1.251323,-0.041182,-0.701677,-2.557421,0.794677
MA1722.2,1.325728,-2.217041,0.549391,-2.215406,-0.650389,0.953926,2.349865,0.252874,0.158069,-0.048560,...,0.845254,-0.899775,-0.017518,-0.497688,-0.028953,-1.504290,-0.401631,-2.806017,0.224433,2.675749