In [1]:
library(parallel)
library(GenomicFeatures)
set.seed(1234)
library(repr)
library(motifmatchr)
library(fastmatch)
library(qlcMatrix)

library(ensembldb)
library(EnsDb.Hsapiens.v86)
library(AnnotationFilter)

library(Signac)
library(Seurat)
library(JASPAR2024)
library(TFBSTools)
library(BSgenome.Hsapiens.UCSC.hg38)
library(patchwork)
library(ggplot2)
library(Matrix)
library(zoo)
library(tidyr)

source("../multiome_methods/function_calls.r")
source("../multiome_methods/peak_gene_relations.r")
source("../multiome_methods/binding_site_identification.r")
source("../multiome_methods/TF_activity.r")
source("../multiome_methods/signac_utils.r")

library(dplyr)

library(ggplot2)
library(hexbin)
library(RColorBrewer)
library(cowplot)
library(gridExtra)
library(ggExtra)

library(pheatmap)
library(purrr)
library(data.table)
library(Rsamtools)
library(stringi)

Loading required package: BiocGenerics

Loading required package: generics


Attaching package: ‘generics’


The following objects are masked from ‘package:base’:

    as.difftime, as.factor, as.ordered, intersect, is.element, setdiff,
    setequal, union



Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, saveRDS, table, tapply, unique,
    unsplit, which.max, which.min


Loading required package: S4Vectors

Loading required package: stats4


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomeInfoDb

Loading required package: GenomicRanges

Loading required package: AnnotationDbi

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


Loading required package: Matrix


Attaching package: ‘Matrix’


The following object is masked from ‘package:S4Vectors’:

    expand


Loading required package: slam

Loading required package: sparsesvd


Attaching package: ‘qlcMatrix’


The following objects are masked from ‘package:Biobase’:

    rowMax, rowMin


Loading required package: AnnotationFilter


Attaching package: 'ensembldb'


The following object is masked from 'package:stats':

    filter



Attaching package: 'Signac'


The following object is masked from 'package:qlcMatrix':

    corSparse


Loading required package: SeuratObject

Loading required package: sp


Attaching package: 'sp'


The following object is masked from 'package:IRanges':

    %over%



Attaching package: 'SeuratObject'


The following object is masked from 'package:GenomicRanges':

    intersect


The following object is masked from 'package:GenomeInfoDb':

    intersect


The following object is masked from 'package:IRanges':

    intersect


The following object is masked from 'package:S4Vectors':

    intersect


The following object is masked from 'package:BiocGenerics':

    intersect


The following objects are masked from 'package:base':

    intersect, t


Loading required package: BiocFileCache

Loading required package: dbplyr


Attaching package: 'TFBSTools'


The following object is masked from 'package:Matrix':

    Matrix


Loading required package: BSgenome

Loading required package: Biostrings

Loading required package: XVector


Attaching package: 'Biostrings'


The following object is masked from 'package:base':

    strsplit


Loading required package: BiocIO

Loading required package: rtracklayer


Attaching package: 'zoo'


The following objects are masked from 'package:base':

    as.Date, as.Date.numeric



Attaching package: 'tidyr'


The following objects are masked from 'package:Matrix':

    expand, pack, unpack


The following object is masked from 'package:S4Vectors':

    expand



Attaching package: 'dplyr'


The following objects are masked from 'package:Biostrings':

    collapse, intersect, setdiff, setequal, union


The following object is masked from 'package:XVector':

    slice


The following objects are masked from 'package:dbplyr':

    ident, sql


The following objects are masked from 'package:ensembldb':

    filter, select


The following object is masked from 'package:fastmatch':

    coalesce


The following object is masked from 'package:AnnotationDbi':

    select


The following object is masked from 'package:Biobase':

    combine


The following objects are masked from 'package:GenomicRanges':

    intersect, setdiff, union


The following object is masked from 'package:GenomeInfoDb':

    intersect


The following objects are masked from 'package:IRanges':

    collapse, desc, intersect, setdiff, slice, union


The following objects are masked from 'package:S4Vectors':

    first, intersect, rename, setdiff, setequal, union


The following objects are masked from 'package:BiocGenerics':

    combine, intersect, setdiff, setequal, union


The following object is masked from 'package:generics':

    explain


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union



Attaching package: 'cowplot'


The following object is masked from 'package:patchwork':

    align_plots



Attaching package: 'gridExtra'


The following object is masked from 'package:dplyr':

    combine


The following object is masked from 'package:Biobase':

    combine


The following object is masked from 'package:BiocGenerics':

    combine



Attaching package: 'purrr'


The following object is masked from 'package:XVector':

    compact


The following object is masked from 'package:Signac':

    reduce


The following object is masked from 'package:qlcMatrix':

    none


The following object is masked from 'package:GenomicRanges':

    reduce


The following object is masked from 'package:IRanges':

    reduce



Attaching package: 'data.table'


The following object is masked from 'package:purrr':

    transpose


The following objects are masked from 'package:dplyr':

    between, first, last


The following objects are masked from 'package:zoo':

    yearmon, yearqtr


The following object is masked from 'package:slam':

    rollup


The following object is masked from 'package:GenomicRanges':

    shift


The following object is masked from 'package:IRanges':

    shift


The following objects are masked from 'package:S4Vectors':

    first, second



Attaching package: 'Rsamtools'


The following objects are masked from 'package:zoo':

    index, index<-

In [2]:
object_w_net <- readRDS("object_w_net_smooth_muscle_contraction.rds")

In [4]:
str(object_w_net@misc, max.level = 1)

List of 12
 $ markers.annotated        :'data.frame':	4000 obs. of  8 variables:
 $ peak_stats               :'data.frame':	134 obs. of  43 variables:
 $ peak_stats.filtered      :'data.frame':	17 obs. of  51 variables:
 $ motifs.inProximalPeaks   :List of 3
 $ motif_enrichment         :'data.frame':	2160 obs. of  16 variables:
 $ motifs.inDistalPeaks     :List of 1
 $ filtered.motif_enrichment:'data.frame':	888 obs. of  16 variables:
 $ motif_stats              :'data.frame':	888 obs. of  26 variables:
 $ motif2TF                 :List of 720
 $ TF2motif                 :List of 668
 $ seedNetwork              :List of 1
 $ context_subNetwork       :List of 1

In [8]:
colnames(object_w_net@misc$peak_stats.filtered)

 [1] "cluster"
 [2] "peak"
 [3] "gene"
 [4] "annotation"
 [5] "regulatorType"
 [6] "signac.scores"
 [7] "signac.zscores"
 [8] "signac.pvalues"
 [9] "t-stat_highly.acc"
[10] "p.value-t.test_highly.acc"
[11] "p.value-t.test_highly.acc_Bonf"
[12] "p.value-t.test_highly.acc_BH"
[13] "expr_not_0"
[14] "acc_not_0"
[15] "expr_not_0.given_acc"
[16] "expr_and_acc_not_0"
[17] "FC.expr_given_acc"
[18] "expr_not_0.bg"
[19] "acc_not_0.bg"
[20] "expr_not_0.given_acc.bg"
[21] "expr_and_acc_not_0.bg"
[22] "FC.expr_given_acc.bg"
[23] "expr_not_0.bg_other_peaks.same_cluster"
[24] "acc_not_0.bg_other_peaks.same_cluster"
[25] "expr_not_0.given_acc.bg_other_peaks.same_cluster"
[26] "expr_and_acc_not_0.bg_other_peaks.same_cluster"
[27] "FC.expr_given_acc.bg_other_peaks.same_cluster"
[28] "n.bg_other_peaks.same_cluster"
[29] "expr_not_0.all"
[30] "acc_not_0.all"
[31] "expr_not_0.given_acc.all"
[32] "expr_and_acc_not_0.all"
[33] "FC.expr_given_acc.all"
[34] "expr_not_0.bg_other_peaks.all"
[35] "acc_not_0.bg_other_peaks.all"
[36] "expr_not_0.given_acc.bg_other_peaks.all"
[37] "expr_and_acc_not_0.bg_other_peaks.all"
[38] "FC.expr_given_acc.bg_other_peaks.all"
[39] "n.bg_other_peaks.all"
[40] "high_cor_distal"
[41] "high_cor_distal_zScore"
[42] "promotersLinkedToSeed"
[43] "distalPeaksLinkedToSeed"
[44] "acc_cells_cluster"
[45] "delta_expr_given_acc.same_peak_bg"
[46] "delta_expr_given_acc.other_peaks.same_cluster"
[47] "delta_expr_given_acc.other_peaks.all"
[48] "pass_cluster_specific"
[49] "pass_global"
[50] "pass_any"
[51] "pass_type"

## explainations peak-stats 
#### Identity columns 
- 'cluster'
- 'peak'
- 'gene'
- 'annotation': seed gene, or module gene (from prior net), or marker gene
- 'regulatorType': proximal: 100-2000 upstream TSS, else distal

#### LinkPeaks stats: across all clusters
- 'signac.scores': The raw Signac link score from Links(object)$score
- 'signac.zscores': The Signac link z-score from Links(object)$zscore
- 'signac.pvalues': The Signac link p-value from Links(object)$pvalue

#### Cluster-specific peak accessibility test columns: conduct_stat_test() using test='t-test', test_activation=TRUE (is this peak more accessible in the target cluster than outside it?)
foreground: cells of cluster,  background: all other cells, alternative: greater
- t-stat_highly.acc: The one-sided t-test statistic for target-cluster accessibility > background accessibility
- p.value-t.test_highly.acc: The raw p-value from that one-sided t-test
- p.value-t.test_highly.acc_Bonf: Bonferroni-adjusted p-value across all unique (cluster, peak) tests
- p.value-t.test_highly.acc_BH: Benjamini–Hochberg adjusted p-value across all unique (cluster, peak) tests

#### Probability / zero-expression columns: zero_expression_stats() and calc_prob_stats(gene_expr, peak_acc)
(n_cells = number of cells in cluster
n_expr = # cells with gene_expr != 0
n_acc = # cells with peak_acc != 0
n_joint = # cells with gene_expr != 0 AND peak_acc != 0)

- expr_not_0 = n_expr / n_cells: Fraction of cells in the target cluster where the gene is expressed
- acc_not_0 = n_acc / n_cells: Fraction of cells in the target cluster where this peak is accessible
- expr_not_0.given_acc = n_joint / n_acc: Conditional probability that the gene is expressed among cells where this peak is accessible, within the target cluster: P(expr != 0 | acc != 0) in the cluster
- expr_and_acc_not_0 = n_joint / n_cells: Joint fraction of target-cluster cells with both gene expression and peak accessibility nonzero: P(expr != 0 AND acc != 0) in the cluster.
- FC.expr_given_acc = expr_not_0.given_acc / expr_not_0: Fold-enrichment of gene expression among accessible cells relative to the cluster baseline expression rate: So values above 1 mean expression is enriched among cells where the peak is open

#### .bg: Background: same peak, other clusters: 
These are computed on the same peak and same gene, but using all cells outside the target cluster.
.all: same peak, All cells:
These are the same metrics as above but computed using all cells for the same gene and same peak.

#### Per-seed peak counts
- 'promotersLinkedToSeed': Number of linked peaks for this (gene, cluster) whose regulatorType == "proximal"
- 'distalPeaksLinkedToSeed': Number of linked peaks for this (gene, cluster) whose regulatorType == "distal"

#### Convenience / derived filter columns
- 'acc_cells_cluster': Estimated number of accessible cells in the target cluster for this peak: acc_cells_cluster = acc_not_0 * cluster_size where cluster_size = table(Idents(object))[cluster]
- 'delta_expr_given_acc.same_peak_bg': Difference in conditional expression between target cluster and background, for the same peak: expr_not_0.given_acc - expr_not_0.given_acc.bg
(- 'delta_expr_given_acc.other_peaks.same_cluster': Difference between the target peak and the “other linked peaks of same gene” summary, inside the target cluster:
expr_not_0.given_acc - expr_not_0.given_acc.bg_other_peaks.same_cluster
'delta_expr_given_acc.other_peaks.all': Difference between the target peak’s across-all-cells conditional expression and the “other linked peaks of same gene” across-all-cells summary: expr_not_0.given_acc.all - expr_not_0.given_acc.bg_other_peaks.all)

#### Final filter flags
- 'pass_cluster_specific'
    - promoter requirement, if enabled: promotersLinkedToSeed > 0
    - p.value-t.test_highly.acc_BH < th
    - t-stat_highly.acc > cluster_t_min
    - acc_cells_cluster >= min.cells
    - expr_and_acc_not_0 >= cluster_expr_given_acc_min
    - expr_not_0.given_acc > expr_given_acc_th
    - FC.expr_given_acc > cluster_fc_min
    - delta_expr_given_acc.same_peak_bg >= cluster_delta_same_peak_bg_min
- 'pass_global'
    - promoter requirement, if enabled
    - signac.zscores >= global_signac_z_min
    - signac.pvalues < global_signac_p_cutoff
    - expr_and_acc_not_0.all >= global_expr_given_acc_min
    - expr_not_0.given_acc.all > expr_given_acc_th
    - FC.expr_given_acc.all > global_fc_min
- 'pass_any': TRUE if pass_cluster_specific | pass_global
- 'pass_type'

In [45]:
summary_col_labels_short <- c(
  gene = "Gene",
  cluster = "Cluster",
  annotation = "Annotation",
  peak = "Peak",
  regulatorType = "Class",
  signac.scores = "Link Score",
  signac.zscores = "Link Z",
  signac.pvalues = "Link P",
  `t-stat_highly.acc` = "Acc. T-stat",
  `p.value-t.test_highly.acc_BH` = "Acc. FDR",
  acc_cells_cluster = "Accessible Cells",
  `expr_not_0.given_acc` = "P(expr|acc), cluster",
  `expr_not_0.given_acc.bg` = "P(expr|acc), bg",
  expr_and_acc_not_0 = "P(expr & acc), cluster",
  expr_and_acc_not_0.all = "P(expr & acc), all",
  FC.expr_given_acc = "Enrichment, cluster",
  FC.expr_given_acc.all = "Enrichment, all",
  delta_expr_given_acc.same_peak_bg = "Delta P(expr|acc)",
  promotersLinkedToSeed = "Promoter Peaks",
  distalPeaksLinkedToSeed = "Distal Peaks",
  pass_type = "Pass Type"
)

In [47]:
# keep only the selected columns, in this order
summary_cols <- c(
  "gene",
  "cluster",
  "annotation",
  "peak",
  "regulatorType",
  "signac.scores",
  "signac.zscores",
  "signac.pvalues",
  "t-stat_highly.acc",
  "p.value-t.test_highly.acc_BH",
  "acc_cells_cluster",
  "expr_not_0.given_acc",
  "expr_not_0.given_acc.bg",
  "expr_and_acc_not_0",
  "expr_and_acc_not_0.all",
  "FC.expr_given_acc",
  "FC.expr_given_acc.all",
  "delta_expr_given_acc.same_peak_bg",
  "promotersLinkedToSeed",
  "distalPeaksLinkedToSeed",
  "pass_type"
)


# filter + rename
peak_stats_summary <- object_w_net@misc$peak_stats.filtered[, summary_cols]
colnames(peak_stats_summary) <- summary_col_labels_short[summary_cols]

peak_stats_summary

    Gene   Cluster Annotation   Peak                     Class    Link Score
1   MYLK   0       module_genes chr3-123766211-123767342 distal   0.09363708
7   MYLK   0       module_genes chr3-123815972-123817188 distal   0.06480712
12  MYLK   0       module_genes chr3-123883475-123884734 proximal 0.05038281
99  KCNMA1 0       module_genes chr10-77636810-77638795  proximal 0.05492740
122 MYH11  0       module_genes chr16-15856768-15857482  proximal 0.06555315
123 MYH11  0       module_genes chr16-15857870-15858601  proximal 0.05493147
98  KCNMA1 0       seed_genes   chr10-77636810-77638795  proximal 0.07448205
120 MYH11  0       seed_genes   chr16-15856768-15857482  proximal 0.09424665
125 MYH11  0       seed_genes   chr16-15857870-15858601  proximal 0.07845987
121 MYH11  0       seed_genes   chr16-15856768-15857482  proximal 0.10421517
124 MYH11  0       seed_genes   chr16-15857870-15858601  proximal 0.18218856
2   MYLK   0       seed_genes   chr3-123766211-123767342 distal   0.06558273
8   MYLK   0       seed_genes   chr3-123815972-123817188 distal   0.19641002
10  MYLK   0       seed_genes   chr3-123883475-123884734 proximal 0.05657609
3   MYLK   0       seed_genes   chr3-123766211-123767342 distal   0.10283242
9   MYLK   0       seed_genes   chr3-123815972-123817188 distal   0.19796779
11  MYLK   0       seed_genes   chr3-123883475-123884734 proximal 0.07301147
    Link Z   Link P       Acc. T-stat Acc. FDR     ⋯ P(expr|acc), cluster
1   3.276845 5.248694e-04 6.141285    2.363083e-09 ⋯ 0.6861314
7   3.966681 3.644017e-05 8.566264    7.019418e-17 ⋯ 0.7169811
12  3.653168 1.295125e-04 8.727091    2.051297e-17 ⋯ 0.6808511
99  4.224431 1.197725e-05 8.838366    9.343907e-18 ⋯ 0.6368564
122 4.334615 7.300771e-06 5.760547    1.868771e-08 ⋯ 0.6875000
123 3.406572 3.289211e-04 7.703362    6.008124e-14 ⋯ 0.7116564
98  2.930289 1.693235e-03 8.838366    9.343907e-18 ⋯ 0.6368564
120 1.802430 3.573887e-02 5.760547    1.868771e-08 ⋯ 0.6875000
125 1.726382 4.213940e-02 7.703362    6.008124e-14 ⋯ 0.7116564
121 3.785588 7.667278e-05 5.760547    1.868771e-08 ⋯ 0.6875000
124 4.853335 6.070129e-07 7.703362    6.008124e-14 ⋯ 0.7116564
2   2.865377 2.082566e-03 6.141285    2.363083e-09 ⋯ 0.6861314
8   2.250333 1.221391e-02 8.566264    7.019418e-17 ⋯ 0.7169811
10  1.843781 3.260751e-02 8.727091    2.051297e-17 ⋯ 0.6808511
3   3.278233 5.222959e-04 6.141285    2.363083e-09 ⋯ 0.6861314
9   4.583405 2.287325e-06 8.566264    7.019418e-17 ⋯ 0.7169811
11  2.387360 8.484925e-03 8.727091    2.051297e-17 ⋯ 0.6808511
    P(expr|acc), bg P(expr & acc), cluster P(expr & acc), all
1   0.3614458       0.06188282             0.02950192
7   0.3384615       0.07504937             0.03026820
12  0.2511848       0.18959842             0.08563218
99  0.1849711       0.15470704             0.06340996
122 0.2439024       0.05069124             0.02049808
123 0.2654321       0.07636603             0.03045977
98  0.1849711       0.15470704             0.06340996
120 0.2439024       0.05069124             0.02049808
125 0.2654321       0.07636603             0.03045977
121 0.2439024       0.05069124             0.02049808
124 0.2654321       0.07636603             0.03045977
2   0.3614458       0.06188282             0.02950192
8   0.3384615       0.07504937             0.03026820
10  0.2511848       0.18959842             0.08563218
3   0.3614458       0.06188282             0.02950192
9   0.3384615       0.07504937             0.03026820
11  0.2511848       0.18959842             0.08563218
    Enrichment, cluster Enrichment, all Delta P(expr|acc) Promoter Peaks
1   1.018801            1.775816        0.3246856         3
7   1.064608            1.910201        0.3785196         3
12  1.010961            1.478984        0.4296662         3
99  1.073679            1.528471        0.4518853         2
122 1.112154            1.787042        0.4435976         6
123 1.151231            1.920139        0.4462243         6
98  1.073679            1.528471        0.4518853         2
120 1.112154            1.787042        0.4435976         6
125 1.151231            1.920139        0.4462243         6
121 1.112154            1.787042        0.4435976         6
124 1.151231            1.920139        0.4462243         6
2   1.018801            1.775816        0.3246856         3
8   1.064608            1.910201        0.3785196         3
10  1.010961            1.478984        0.4296662         3
3   1.018801            1.775816        0.3246856         3
9   1.064608            1.910201        0.3785196         3
11  1.010961            1.478984        0.4296662         3
    Distal Peaks Pass Type
1    9           cluster_specific
7    9           cluster_specific
12   9           cluster_specific
99   6           cluster_specific
122  6           cluster_specific
123  6           cluster_specific
98   6           cluster_specific
120  6           cluster_specific
125  6           cluster_specific
121  6           cluster_specific
124  6           cluster_specific
2    9           cluster_specific
8    9           cluster_specific
10   9           cluster_specific
3    9           cluster_specific
9    9           cluster_specific
11   9           cluster_specific

In [48]:
write.csv(peak_stats_summary, "exmpl_results_breast/peak_stats_summary_smooth_muscle_contraction.csv", row.names = FALSE)

## motif stats: Motif enrichment and footprint scoring
#### Identity Columns
- cluster
- gene
- motif
- TF: Transcription factor that binds motif (if multiple, new row for each)

#### Motif enrichment in linked peaks: motif_enrichment_per_gene() / calculate_enrichments()
logic: 
1. find peaks linked to the gene in the chosen cluster
2. split them into proximal vs distal using regulatorType
3. count how often each motif occurs in those linked peaks
4. compare that to a random background made by replacing each linked peak with a sampled “comparable”(GC content and length) peak from the same peak meta-feature cluster. t-test for enrichment
-> for this: make clusters of comparable peaks, store in object$peaks@meta.features$cluster
##### Proximal motif columns
- proximal.motif_count: The number of occurrences of this motif in proximal peaks linked to the gene in this cluster
- proximal.background_count: The mean motif count in matched random background peak sets for the proximal linked peaks. For each background draw, every linked proximal peak is replaced by a sampled peak from the same object$peaks@meta.features$cluster, then motif counts are computed, and the mean over draws is stored here
- log2FC.proximal: log2(proximal.motif_count / proximal.background_count): log2 enrichment of proximal motif count over matched background. Positive values mean enrichment; zero means no enrichment; negative values mean depletion
- t_stat.proximal: The t-statistic from testing the proximal background distribution against the foreground proximal count using
t.test(col_bg, mu = value_fg, alternative = "less") in effect. Interpreted practically, small p-values support that the background mean is lower than the foreground count, i.e. the motif is enriched in the linked proximal peaks.
- p_value.proximal: The raw p-value for that proximal enrichment test.
- p_adjust.proximal: A simple multiplicity-adjusted proximal p-value, computed as raw p_value.proximal * number_of_motifs, then capped at 1. This is Bonferroni-like, not BH/FDR.

##### Distal motif columns: analog to proximal, but using distal peaks
- distal.motif_count
- distal.background_count
- log2FC.distal = log2(distal.motif_count / distal.background_count)
- t_stat.distal
- p_value.distal
- p_adjust.distal

##### Promoter motif column
- promoter.motif_count: The number of occurrences of this motif in the gene’s promoter sequence, regardless of whether there is an accessible linked peak there. This is computed by get_tf_bindingsites_in_region(), which scans the promoter DNA sequence with the motif PWM. The promoter length: 2000 bp upstream TSS, but it may be extended if the gene has proximal linked peaks farther upstream than 2 kb.

#### Footprint columns: add_motif_stats() -> footprint_stats_test() for each  (gene, cluster, motif)
idea: The foreground footprint is built from motif sites found in peaks linked to the gene; the background footprint distribution is built by repeatedly sampling the same number of motif sites of that motif from elsewhere and rescoring them
core = mean.footprint - mean.flanks
- difference = observed.insertions_normalized - expected.insertions 
- mean.flanks = mean(difference in left + right flank windows)
- mean.footprint = mean(difference in motif-core window)
more negative footprint_score means the motif center is more depleted relative to the flanks, which is the classic “footprint” pattern
values near 0 mean little difference between core and flanks
positive values would mean the core is more accessible than the flanks

observed.insertions_normalized: empirical insertion profile around the motif sites, normalized by its global mean (it is the mean observed Tn5 insertion signal at each relative position, normalized so the average across positions is 1)
expected.insertions: sequence-bias-based expected insertion profile, normalized by flank expectation  (comes from GetExpectedInsertion(), which extracts the DNA sequence around the motif regions, gets the assay’s Tn5 bias vector, and calls FindExpectedInsertions(). That helper computes the expected insertion profile from local sequence composition and Tn5 hexamer bias, then normalizes that expected profile by the mean of the flank positions.)

##### Footprint statistic columns
- footprint_scores: as explained above
- bg_size: how many bg scores where computed
- bg_footprint_mean: The mean of the background footprint scores across those sampled background footprints
- footprint.t_stat: t.test(x = background_scores, mu = foreground_score, alternative = "greater"): So the test is asking whether the background mean score is greater than the foreground score. Because more negative scores are stronger footprints in your setup, a small p-value supports the foreground having a stronger depletion footprint than background
- footprint.p_value: The raw p-value for that footprint-vs-background test.
- footprint.p_value_adj: A per-(gene, cluster) multiplicity-adjusted version of footprint.p_value. In add_motif_stats(), after all motif rows are combined, the code multiplies each raw footprint p-value by the number of motif rows for that same gene and cluster, then caps at 1. So again this is Bonferroni-like, not BH/FDR.

##### Footprint quality / coverage columns
- sd.flanks: The standard deviation of the flank difference values for the foreground footprint. This is a variability measure for the left/right flank regions around the motif
- bg_sd_mean: The mean of the flank standard deviations across the sampled background footprints
- left_flank_nonzero_positions: How many positions in the left flank had nonzero observed insertion counts in the foreground footprint pileup. It is computed from observed.insertions.counts_sum in the footprint plot data
- right_flank_nonzero_positions: same for right flank

In [56]:

motif2TF_df <- data.frame(
  motif = rep(names(object_w_net@misc$motif2TF),
              lengths(object_w_net@misc$motif2TF)),
  TF = unlist(object_w_net@misc$motif2TF, use.names = FALSE),
  stringsAsFactors = FALSE
)

head(motif2TF_df)

  motif    TF
1 MA0069.1 PAX6
2 MA0071.1 RORA
3 MA0074.1 RXRA
4 MA0074.1 VDR
5 MA0101.1 REL
6 MA0107.1 RELA

In [57]:

tmp <- object_w_net@misc$motif_stats %>%
  left_join(motif2TF_df, by = "motif")

Warning message in left_join(., motif2TF_df, by = "motif"):
"Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 89 of `x` matches multiple rows in `y`.
ℹ Row 5 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning."

In [52]:
motif_summary_cols <- c(
  "gene",
  "cluster",
  "TF",
  "motif",
  "proximal.motif_count",
  "proximal.background_count",
  "log2FC.proximal",
  "p_adjust.proximal",
  "distal.motif_count",
  "distal.background_count",
  "log2FC.distal",
  "p_adjust.distal",
  "promoter.motif_count",
  "footprint_score",
  "bg_footprint_mean",
  "footprint.p_value_adj",
  "bg_size",
  "sd.flanks",
  "bg_sd_mean",
  "left_flank_nonzero_positions",
  "right_flank_nonzero_positions"
)

In [60]:
motif_summary_col_labels <- c(
  gene = "Gene",
  cluster = "Cluster",
  TF = "TF",
  motif = "Motif",
  proximal.motif_count = "Prox Motif count",
  proximal.background_count = "Prox Bg count",
  log2FC.proximal = "Prox Log2FC",
  p_adjust.proximal = "Prox p-value adj",
  distal.motif_count = "Dist Motif count",
  distal.background_count = "Dist Bg count",
  log2FC.distal = "Dist Log2FC",
  p_adjust.distal = "Dist p-value adj",
  promoter.motif_count = "Prom Motif count",
  footprint_score = "FP Score",
  bg_footprint_mean = "Bg FP Score",
  footprint.p_value_adj = "FP p-value adj",
  bg_size = "Bg Size",
  sd.flanks = "Flank sd",
  bg_sd_mean = "Bg Flank sd",
  left_flank_nonzero_positions = "Left Flank != 0",
  right_flank_nonzero_positions = "Right Flank != 0"
)

In [58]:
colnames(tmp)

 [1] "gene"                          "cluster"
 [3] "proximal.motif_count"          "proximal.background_count"
 [5] "log2FC.proximal"               "t_stat.proximal"
 [7] "p_value.proximal"              "p_adjust.proximal"
 [9] "distal.motif_count"            "distal.background_count"
[11] "log2FC.distal"                 "t_stat.distal"
[13] "p_value.distal"                "p_adjust.distal"
[15] "motif"                         "promoter.motif_count"
[17] "footprint_score"               "bg_size"
[19] "bg_footprint_mean"             "footprint.t_stat"
[21] "footprint.p_value"             "footprint.p_value_adj"
[23] "sd.flanks"                     "bg_sd_mean"
[25] "left_flank_nonzero_positions"  "right_flank_nonzero_positions"
[27] "TF"

In [61]:
motif_stats_summary <- tmp[, motif_summary_cols]
colnames(motif_stats_summary) <- motif_summary_col_labels[motif_summary_cols]

motif_stats_summary

    Gene   Cluster TF         Motif    Prox Motif count Prox Bg count
1   KCNMA1 0       REL        MA0101.1 1                0.84
2   KCNMA1 0       REL        MA0101.1 1                0.84
3   KCNMA1 0       RELA       MA0107.1 1                1
4   KCNMA1 0       RELA       MA0107.1 1                1
5   KCNMA1 0       EWSR1-FLI1 MA0149.1 10               6.5
6   KCNMA1 0       EWSR1-FLI1 MA0149.1 10               6.5
7   KCNMA1 0       INSM1      MA0155.1 3                2.6
8   KCNMA1 0       INSM1      MA0155.1 3                2.6
9   KCNMA1 0       PLAG1      MA0163.1 1                4.8
10  KCNMA1 0       PLAG1      MA0163.1 1                4.8
11  KCNMA1 0       KLF5       MA0599.1 3                16
12  KCNMA1 0       KLF5       MA0599.1 3                16
13  KCNMA1 0       FOXG1      MA0613.1 1                0.14
14  KCNMA1 0       FOXG1      MA0613.1 1                0.14
15  KCNMA1 0       MSC        MA0665.1 1                0.88
16  KCNMA1 0       MSC        MA0665.1 1                0.88
17  KCNMA1 0       ZIC1       MA0696.1 1                2.6
18  KCNMA1 0       ZIC1       MA0696.1 1                2.6
19  KCNMA1 0       KLF16      MA0741.1 2                10
20  KCNMA1 0       KLF16      MA0741.1 2                10
21  KCNMA1 0       MEIS2      MA0774.1 1                0.44
22  KCNMA1 0       MEIS2      MA0774.1 1                0.44
23  KCNMA1 0       PKNOX2     MA0783.1 2                0.28
24  KCNMA1 0       PKNOX2     MA0783.1 2                0.28
25  KCNMA1 0       TGIF1      MA0796.1 1                0.16
26  KCNMA1 0       TGIF1      MA0796.1 1                0.16
27  KCNMA1 0       TGIF2      MA0797.1 1                0.18
28  KCNMA1 0       TGIF2      MA0797.1 1                0.18
29  KCNMA1 0       TFAP2B     MA0813.1 1                3.4
30  KCNMA1 0       TFAP2B     MA0813.1 1                3.4
⋮   ⋮      ⋮       ⋮          ⋮        ⋮                ⋮
902 MYLK   0       ZIC5       MA1584.2 1                2.9
903 MYLK   0       ZIC5       MA1584.2 1                2.9
904 MYLK   0       ZIC5       MA1584.2 1                2.9
905 MYLK   0       ZIM3       MA1709.2 1                1.7
906 MYLK   0       ZIM3       MA1709.2 1                1.7
907 MYLK   0       ZIM3       MA1709.2 1                1.7
908 MYLK   0       ZNF140     MA1589.2 3                1.9
909 MYLK   0       ZNF140     MA1589.2 3                1.9
910 MYLK   0       ZNF140     MA1589.2 3                1.9
911 MYLK   0       ZNF148     MA1653.2 5                23
912 MYLK   0       ZNF148     MA1653.2 5                23
913 MYLK   0       ZNF148     MA1653.2 5                23
914 MYLK   0       ZNF16      MA1654.2 1                4.1
915 MYLK   0       ZNF16      MA1654.2 1                4.1
916 MYLK   0       ZNF16      MA1654.2 1                4.1
917 MYLK   0       ZNF281     MA1630.3 1                22
918 MYLK   0       ZNF281     MA1630.3 1                22
919 MYLK   0       ZNF281     MA1630.3 1                22
920 MYLK   0       ZNF343     MA1711.2 1                3.1
921 MYLK   0       ZNF343     MA1711.2 1                3.1
922 MYLK   0       ZNF343     MA1711.2 1                3.1
923 MYLK   0       ZNF549     MA1728.2 1                4.7
924 MYLK   0       ZNF549     MA1728.2 1                4.7
925 MYLK   0       ZNF549     MA1728.2 1                4.7
926 MYLK   0       ZNF652     MA1657.2 1                0.98
927 MYLK   0       ZNF652     MA1657.2 1                0.98
928 MYLK   0       ZNF652     MA1657.2 1                0.98
929 MYLK   0       ZSCAN31    MA1722.2 1                0.76
930 MYLK   0       ZSCAN31    MA1722.2 1                0.76
931 MYLK   0       ZSCAN31    MA1722.2 1                0.76
    Prox Log2FC Prox p-value adj Dist Motif count Dist Bg count ⋯
1   0.25        1                0                0             ⋯
2   0.25        1                0                0             ⋯
3   0           1                0                0             ⋯
4   0           1                0                0             ⋯
5   0.62        0.00062          0                0             ⋯
6   0.62        0.00062          0                0             ⋯
7   0.21        1                0                0             ⋯
8   0.21        1                0                0             ⋯
9   -2.3        1                0                0             ⋯
10  -2.3        1                0                0             ⋯
11  -2.4        1                0                0             ⋯
12  -2.4        1                0                0             ⋯
13  2.8         5.3e-20          0                0             ⋯
14  2.8         5.3e-20          0                0             ⋯
15  0.18        1                0                0             ⋯
16  0.18        1                0                0             ⋯
17  -1.4        1                0                0             ⋯
18  -1.4        1                0                0             ⋯
19  -2.3        1                0                0             ⋯
20  -2.3        1                0                0             ⋯
21  1.2         0.00014          0                0             ⋯
22  1.2         0.00014          0                0             ⋯
23  2.8         1.1e-22          0                0             ⋯
24  2.8         1.1e-22          0                0             ⋯
25  2.6         1.4e-14          0                0             ⋯
26  2.6         1.4e-14          0                0             ⋯
27  2.5         1.1e-13          0                0             ⋯
28  2.5         1.1e-13          0                0             ⋯
29  -1.8        1                0                0             ⋯
30  -1.8        1                0                0             ⋯
⋮   ⋮           ⋮                ⋮                ⋮             ⋱
902 -1.5        1                0                0.82          ⋯
903 -1.5        1                0                0.82          ⋯
904 -1.5        1                0                0.82          ⋯
905 -0.77       1                2                5.6           ⋯
906 -0.77       1                2                5.6           ⋯
907 -0.77       1                2                5.6           ⋯
908 0.66        0.006            0                2.4           ⋯
909 0.66        0.006            0                2.4           ⋯
910 0.66        0.006            0                2.4           ⋯
911 -2.2        1                0                4.5           ⋯
912 -2.2        1                0                4.5           ⋯
913 -2.2        1                0                4.5           ⋯
914 -2          1                2                3.8           ⋯
915 -2          1                2                3.8           ⋯
916 -2          1                2                3.8           ⋯
917 -4.5        1                2                4.8           ⋯
918 -4.5        1                2                4.8           ⋯
919 -4.5        1                2                4.8           ⋯
920 -1.6        1                1                1.2           ⋯
921 -1.6        1                1                1.2           ⋯
922 -1.6        1                1                1.2           ⋯
923 -2.2        1                0                3.3           ⋯
924 -2.2        1                0                3.3           ⋯
925 -2.2        1                0                3.3           ⋯
926 0.029       1                0                2.5           ⋯
927 0.029       1                0                2.5           ⋯
928 0.029       1                0                2.5           ⋯
929 0.4         1                0                1.2           ⋯
930 0.4         1                0                1.2           ⋯
931 0.4         1                0                1.2           ⋯
    Dist p-value adj Prom Motif count FP Score Bg FP Score FP p-value adj
1   0                1                -0.34150  0.04059    1.000
2   0                1                -0.34150 -0.49050    1.000
3   0                2                -0.34150 -0.40420    1.000
4   0                2                -0.34150 -0.31480    1.000
5   0                0                 0.02615  0.07307    1.000
6   0                0                 0.02615  0.29410    0.530
7   0                1                 0.34600 -0.20790    1.000
8   0                1                 0.34600 -0.10530    1.000
9   0                0                -0.06973  0.17060    1.000
10  0                0                -0.06973 -0.02619    1.000
11  0                7                -0.09593 -0.46270    1.000
12  0                7                -0.09593 -0.53390    1.000
13  0                0                -0.58400  0.60850    0.300
14  0                0                -0.58400  0.56610    1.000
15  0                2                -0.83850  0.24340    0.019
16  0                2                -0.83850  0.62570    0.190
17  0                2                -1.21400 -0.10180    0.660
18  0                2                -1.21400 -0.30050    0.490
19  0                1                 0.40470 -0.52230    1.000
20  0                1                 0.40470 -0.20500    1.000
21  0                5                 0.20200  0.31260    1.000
22  0                5                 0.20200  0.06002    1.000
23  0                1                -0.32860 -0.16050    1.000
24  0                1                -0.32860 -0.25330    1.000
25  0                0                -0.59770  0.51570    1.000
26  0                0                -0.59770 -0.20250    1.000
27  0                0                -0.59770  0.05560    1.000
28  0                0                -0.59770 -0.97310    1.000
29  0                1                -0.59730 -0.25080    1.000
30  0                1                -0.59730 -0.75870    1.000
⋮   ⋮                ⋮                ⋮        ⋮           ⋮
902 1                0                -0.47610 -0.55410    1.0e+00
903 1                0                -0.47610 -0.36980    1.0e+00
904 1                0                -0.47610 -0.33810    1.0e+00
905 1                0                -0.63750  0.32460    2.2e-04
906 1                0                -0.63750  0.20300    2.5e-04
907 1                0                -0.63750  0.25830    2.0e-01
908 1                0                 0.30190 -0.01796    1.0e+00
909 1                0                 0.30190 -0.18410    1.0e+00
910 1                0                 0.30190  0.03650    1.0e+00
911 1                5                -0.63510 -0.30210    7.5e-01
912 1                5                -0.63510 -0.39440    1.0e+00
913 1                5                -0.63510 -0.27420    1.0e+00
914 1                0                 0.19620 -0.09918    1.0e+00
915 1                0                 0.19620  0.14710    1.0e+00
916 1                0                 0.19620  0.19770    1.0e+00
917 1                5                -0.69320 -0.18110    1.0e+00
918 1                5                -0.69320 -0.47240    1.0e+00
919 1                5                -0.69320 -0.11790    3.3e-01
920 1                0                -1.14800  0.18710    8.1e-05
921 1                0                -1.14800 -0.26030    3.5e-03
922 1                0                -1.14800 -0.12070    3.2e-04
923 1                2                -0.07289 -0.60740    1.0e+00
924 1                2                -0.07289 -0.39730    1.0e+00
925 1                2                -0.07289 -0.42580    1.0e+00
926 1                1                 0.12560  0.26450    1.0e+00
927 1                1                 0.12560  0.07253    1.0e+00
928 1                1                 0.12560 -0.14580    1.0e+00
929 1                0                 0.67400  0.01035    1.0e+00
930 1                0                 0.67400 -0.42520    1.0e+00
931 1                0                 0.67400  0.24390    1.0e+00
    Bg Size Flank sd Bg Flank sd Left Flank != 0 Right Flank != 0
1   20      1.939    3.354        3               3
2   20      1.939    3.927        3               3
3   20      1.939    3.314        3               3
4   20      1.939    3.670        3               3
5   20      1.019    1.194       17              20
6   20      1.019    1.023       17              20
7   20      1.265    2.255        9              11
8   20      1.265    2.090        9              11
9   20      2.218    3.250        4               7
10  20      2.218    3.091        4               7
11  20      1.962    1.828        9              15
12  20      1.962    1.870        9              15
13  20      3.445    4.154        1               6
14  20      3.445    4.699        1               6
15  20      2.822    3.522        4               0
16  20      2.822    4.019        4               0
17  20      3.117    3.507        8               6
18  20      3.117    3.854        8               6
19  20      1.840    2.065       12              14
20  20      1.840    2.016       12              14
21  20      1.909    3.882        0               2
22  20      1.909    3.480        0               2
23  20      2.087    3.018        3               4
24  20      2.087    2.891        3               4
25  20      3.253    4.351        0               4
26  20      3.253    3.737        0               4
27  20      3.253    4.341        0               4
28  20      3.253    4.994        0               4
29  20      1.769    3.227        5               5
30  20      1.769    2.751        5               5
⋮   ⋮       ⋮        ⋮           ⋮               ⋮
902 20      2.321    2.799       12              10
903 20      2.321    3.512       12              10
904 20      2.321    3.207       12              10
905 20      1.830    2.064       13              15
906 20      1.830    2.073       13              15
907 20      1.830    2.261       13              15
908 20      1.224    2.344       13              14
909 20      1.224    2.044       13              14
910 20      1.224    2.150       13              14
911 20      2.467    1.341       15              16
912 20      2.467    1.373       15              16
913 20      2.467    1.331       15              16
914 20      1.711    2.061        6               9
915 20      1.711    2.022        6               9
916 20      1.711    1.987        6               9
917 20      1.409    1.898       11              12
918 20      1.409    1.864       11              12
919 20      1.409    1.875       11              12
920 20      2.067    2.117        8               6
921 20      2.067    2.209        8               6
922 20      2.067    2.146        8               6
923 20      2.162    4.892       10              11
924 20      2.162    3.948       10              11
925 20      2.162    4.506       10              11
926 20      2.754    4.179        5               8
927 20      2.754    3.915        5               8
928 20      2.754    4.082        5               8
929 20      2.671    3.226        6               3
930 20      2.671    4.899        6               3
931 20      2.671    3.698        6               3

In [62]:
write.csv(motif_stats_summary, "exmpl_results_breast/motif_stats_summary_smooth_muscle_contraction.csv", row.names = FALSE)

## network

In [26]:
head(object_w_net@misc$context_subNetwork$smooth_muscle_contraction_cluster_0_genes_with_peaks)

         from  to     color  priorTF reg_type in.prom
KCNMA1.1 REL   KCNMA1 red    FALSE   1        3
KCNMA1.2 RELA  KCNMA1 red    FALSE   1        3
KCNMA1.3 PLAG1 KCNMA1 red    FALSE   1        1
KCNMA1.4 FOXG1 KCNMA1 yellow FALSE   1        1
KCNMA1.5 MSC   KCNMA1 yellow FALSE   1        3
KCNMA1.6 ZIC1  KCNMA1 yellow FALSE   1        3

In [27]:
library(dplyr)
library(jsonlite)

Attaching package: 'jsonlite'


The following object is masked from 'package:purrr':

    flatten

In [1]:
library(dplyr)
library(jsonlite)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [29]:

# assumed columns: from, to, color, priorTF, reg_type, in.prom
df <- object_w_net@misc$context_subNetwork$smooth_muscle_contraction_cluster_0_genes_with_peaks
links <- df %>%
  transmute(
    source = from,
    target = to,
    edge_color = color,
    edge_width = reg_type,
    edge_dash = ifelse(in.prom == 1, "4,4", "0")
  )

# node table
from_nodes <- df %>%
  distinct(name = from, priorTF) %>%
  mutate(type = "from")

to_nodes <- df %>%
  distinct(name = to) %>%
  mutate(priorTF = NA, type = "to")

nodes <- bind_rows(from_nodes, to_nodes) %>%
  group_by(name) %>%
  summarise(
    priorTF = dplyr::first(na.omit(priorTF)),
    type = ifelse(any(type == "from"), "from", "to"),
    .groups = "drop"
  ) %>%
  mutate(
    node_fill = case_when(
      type == "to" ~ "#cccccc",          # default for target nodes
      priorTF %in% TRUE ~ "#ff7f0e",     # prior TF
      priorTF %in% FALSE ~ "#1f77b4",    # not prior TF
      TRUE ~ "#999999"
    )
  )

# convert source/target names to node indices for D3
nodes <- nodes %>% mutate(id = row_number() - 1)

links <- links %>%
  left_join(nodes %>% select(source = name, source_id = id), by = "source") %>%
  left_join(nodes %>% select(target = name, target_id = id), by = "target") %>%
  transmute(
    source = source_id,
    target = target_id,
    edge_color,
    edge_width,
    edge_dash
  )

graph <- list(
  nodes = nodes,
  links = links
)

In [31]:
graph

$nodes
# A tibble: 146 × 5
   name    priorTF type  node_fill    id
   <chr>   <lgl>   <chr> <chr>     <dbl>
 1 ASCL1   FALSE   from  #1f77b4       0
 2 BCL6B   FALSE   from  #1f77b4       1
 3 BHLHE22 FALSE   from  #1f77b4       2
 4 BHLHE41 FALSE   from  #1f77b4       3
 5 CREB3L1 FALSE   from  #1f77b4       4
 6 CREB3L4 FALSE   from  #1f77b4       5
 7 CTCF    FALSE   from  #1f77b4       6
 8 DUX4    FALSE   from  #1f77b4       7
 9 E2F8    FALSE   from  #1f77b4       8
10 ERF     FALSE   from  #1f77b4       9
# ℹ 136 more rows

$links
    source target edge_color edge_width edge_dash
1       77     33        red          1         0
2       78     33        red          1         0
3       61     33        red          1       4,4
4       21     33     yellow          1       4,4
5       44     33     yellow          1         0
6      119     33     yellow          1         0
7       60     33        red          1         0
8      110     33        red          1       4,4
9      111     33        red          1       4,4
10     105     33        red          1         0
11      14     33      green          1         0
12     112     33        red          1       4,4
13     113     33        red          1       4,4
14     125     33        red          1       4,4
15     135     33     yellow          1       4,4
16       0     33        red          1         0
17       2     33        red          1         0
18       6     33        red          1       4,4
19       9     33        red          1       4,4
20      28     33        red          1       4,4
21      12     33        red          1       4,4
22      15     33        red          1       4,4
23      18     33        red          1       4,4
24      19     33     yellow          1       4,4
25      20     33     yellow          1       4,4
26      22     33     yellow          1       4,4
27     103     33        red          1         0
28      26     33        red          1       4,4
29      27     33        red          1         0
30      40     33        red          1       4,4
31      45     33        red          1         0
32      49     33        red          1         0
33      51     33      green          1       4,4
34      55     33        red          1       4,4
35      58     33        red          1       4,4
36      80     33        red          1       4,4
37      74     33     yellow          1         0
38      79     33      green          1         0
39      84     33        red          1         0
40     102     33        red          1         0
41     108     33        red          1       4,4
42      10     33        red          1       4,4
43     120     33     yellow          1         0
44     121     33      green          1         0
45     124     33      green          1         0
46     131     33        red          1       4,4
47     132     33        red          1       4,4
48     133     33        red          1       4,4
49     138     33        red          1         0
50     139     33        red          1       4,4
51     142     33      green          1       4,4
52     145     33      green          1       4,4
53      77     47        red          1         0
54      52     47      green          1       4,4
55     115     47      green          1       4,4
56      13     47      green          1       4,4
57      61     47        red          1       4,4
58     119     47        red          1         0
59      75     47     yellow          1       4,4
60     105     47      green          1         0
61     106     47        red          1         0
62     104     47      green          1         0
63     136     47        red          1       4,4
64     118     47     yellow          1         0
65     127     47        red          1         0
66      15     47        red          1         0
67      11     47        red          1       4,4
68      28     47        red          1       4,4
69      23     47        red          1         0
70      30     47     yellow          1         0
71      46     47        red          1         0
72      50     47     yellow          1         0
73      51     47      green          1       4,4
74      53     47      green          1         0
75      57     47        red          1         0
76      73     47     yellow          1         0
77      74     47        red          1       4,4
78      81     47     yellow          1       4,4
79      76     47        red          1         0
80      83     47     yellow          1         0
81      85     47     yellow          1         0
82      98     47        red          1       4,4
83     107     47      green          1         0
84     114     47        red          1         0
85     117     47        red          1         0
86     123     47      green          1       4,4
87     129     47      green          1         0
88     134     47        red          1       4,4
89     137     47     yellow          1         0
90     140     47        red          1         0
91     141     47        red          1       4,4
92     143     47        red          1         0
93     144     47     yellow          1         0
94     145     47        red          1       4,4
95      82     48       blue          2       4,4
96     101     48       blue          2       4,4
97     109     48       blue          2       4,4
98      29     48     yellow          1         0
99      61     48        red          1       4,4
100      7     48        red          1         0
101     99     48        red          1       4,4
102    100     48     yellow          2       4,4
103     37     48        red          1         0
104      3     48        red          2       4,4
105     43     48        red          1       4,4
106      1     48      green          1       4,4
107     35     48        red          1         0
108     68     48        red          1         0
109     69     48        red          1       4,4
110     70     48     yellow          1         0
111     72     48        red          1         0
112    127     48        red          1       4,4
113    128     48        red          1       4,4
114     94     48      green          1         0
115     96     48        red          1         0
116     34     48        red          1         0
117     89     48        red          1         0
118      4     48        red          1       4,4
119      5     48        red          1       4,4
120      8     48        red          1         0
121     16     48     yellow          1       4,4
122     32     48     yellow          1       4,4
123     17     48        red          1       4,4
124     31     48        red          1       4,4
125     90     48     yellow          1         0
126     23     48        red          1         0
127     24     48        red          1         0
128     25     48        red          1         0
129     36     48        red          1         0
130     38     48        red          1         0
131     39     48        red          1         0
132     41     48        red          1         0
133     42     48     yellow          1         0
134     54     48        red          1       4,4
135     80     48        red          2       4,4
136     56     48      green          1         0
137     59     48     yellow          1         0
138     62     48        red          1         0
139     63     48        red          1       4,4
140     64     48        red          1         0
141     65     48     yellow          1         0
142     66     48        red          1         0
143     67     48        red          1         0
144     71     48        red          1         0
145     74     48     yellow          1         0
146     76     48        red          1         0
147     86     48     yellow          1       4,4
148     87     48      green          1       4,4
149     88     48      green          1         0
150     91     48      green          1         0
151     92     48        red          1         0
152     93     48      green          1         0
153     95     48        red          1         0
154     97     48     yellow          1         0
155    116     48      green          1         0
156    121     48        red          1       4,4
157    122     48      green          1       4,4
158    126     48        red          1         0
159    130     48     yellow          1         0
160    133     48      green          1       4,4

In [32]:

write_json(graph, "exmpl_results_breast/graph.json", auto_unbox = TRUE, pretty = TRUE)